// automatically generated by the FlatBuffers compiler, do not modify

 

import * as flatbuffers from 'flatbuffers';

import { RenderedFaces } from '../../openskp/fragments-fb/rendered-faces.js';
import { Stroke } from '../../openskp/fragments-fb/stroke.js';


export class Material {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Material {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

r():number {
  return this.bb!.readUint8(this.bb_pos);
}

g():number {
  return this.bb!.readUint8(this.bb_pos + 1);
}

b():number {
  return this.bb!.readUint8(this.bb_pos + 2);
}

a():number {
  return this.bb!.readUint8(this.bb_pos + 3);
}

renderedFaces():RenderedFaces {
  return this.bb!.readInt8(this.bb_pos + 4);
}

stroke():Stroke {
  return this.bb!.readInt8(this.bb_pos + 5);
}

static sizeOf():number {
  return 6;
}

static createMaterial(builder:flatbuffers.Builder, r: number, g: number, b: number, a: number, rendered_faces: RenderedFaces, stroke: Stroke):flatbuffers.Offset {
  builder.prep(1, 6);
  builder.writeInt8(stroke);
  builder.writeInt8(rendered_faces);
  builder.writeInt8(a);
  builder.writeInt8(b);
  builder.writeInt8(g);
  builder.writeInt8(r);
  return builder.offset();
}

}
