// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable, constant_identifier_names

library openskp._fragments_fb;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;



enum RenderedFaces {
  ONE(0),
  TWO(1);

  final int value;
  const RenderedFaces(this.value);

  factory RenderedFaces.fromValue(int value) {
    switch (value) {
      case 0: return RenderedFaces.ONE;
      case 1: return RenderedFaces.TWO;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static RenderedFaces? _createOrNull(int? value) =>
      value == null ? null : RenderedFaces.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 1;
  static const fb.Reader<RenderedFaces> reader = _RenderedFacesReader();
}

class _RenderedFacesReader extends fb.Reader<RenderedFaces> {
  const _RenderedFacesReader();

  @override
  int get size => 1;

  @override
  RenderedFaces read(fb.BufferContext bc, int offset) =>
      RenderedFaces.fromValue(const fb.Int8Reader().read(bc, offset));
}

enum Stroke {
  DEFAULT(0);

  final int value;
  const Stroke(this.value);

  factory Stroke.fromValue(int value) {
    switch (value) {
      case 0: return Stroke.DEFAULT;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static Stroke? _createOrNull(int? value) =>
      value == null ? null : Stroke.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 0;
  static const fb.Reader<Stroke> reader = _StrokeReader();
}

class _StrokeReader extends fb.Reader<Stroke> {
  const _StrokeReader();

  @override
  int get size => 1;

  @override
  Stroke read(fb.BufferContext bc, int offset) =>
      Stroke.fromValue(const fb.Int8Reader().read(bc, offset));
}

enum AxisPartClass {
  NONE(0),
  WIRE(1),
  WIRE_SET(2),
  CIRCLE_CURVE(3);

  final int value;
  const AxisPartClass(this.value);

  factory AxisPartClass.fromValue(int value) {
    switch (value) {
      case 0: return AxisPartClass.NONE;
      case 1: return AxisPartClass.WIRE;
      case 2: return AxisPartClass.WIRE_SET;
      case 3: return AxisPartClass.CIRCLE_CURVE;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static AxisPartClass? _createOrNull(int? value) =>
      value == null ? null : AxisPartClass.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 3;
  static const fb.Reader<AxisPartClass> reader = _AxisPartClassReader();
}

class _AxisPartClassReader extends fb.Reader<AxisPartClass> {
  const _AxisPartClassReader();

  @override
  int get size => 1;

  @override
  AxisPartClass read(fb.BufferContext bc, int offset) =>
      AxisPartClass.fromValue(const fb.Int8Reader().read(bc, offset));
}

enum RepresentationClass {
  NONE(0),
  SHELL(1),
  CIRCLE_EXTRUSION(2);

  final int value;
  const RepresentationClass(this.value);

  factory RepresentationClass.fromValue(int value) {
    switch (value) {
      case 0: return RepresentationClass.NONE;
      case 1: return RepresentationClass.SHELL;
      case 2: return RepresentationClass.CIRCLE_EXTRUSION;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static RepresentationClass? _createOrNull(int? value) =>
      value == null ? null : RepresentationClass.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 2;
  static const fb.Reader<RepresentationClass> reader = _RepresentationClassReader();
}

class _RepresentationClassReader extends fb.Reader<RepresentationClass> {
  const _RepresentationClassReader();

  @override
  int get size => 1;

  @override
  RepresentationClass read(fb.BufferContext bc, int offset) =>
      RepresentationClass.fromValue(const fb.Int8Reader().read(bc, offset));
}

enum ShellType {
  NONE(0),
  BIG(1);

  final int value;
  const ShellType(this.value);

  factory ShellType.fromValue(int value) {
    switch (value) {
      case 0: return ShellType.NONE;
      case 1: return ShellType.BIG;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static ShellType? _createOrNull(int? value) =>
      value == null ? null : ShellType.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 1;
  static const fb.Reader<ShellType> reader = _ShellTypeReader();
}

class _ShellTypeReader extends fb.Reader<ShellType> {
  const _ShellTypeReader();

  @override
  int get size => 1;

  @override
  ShellType read(fb.BufferContext bc, int offset) =>
      ShellType.fromValue(const fb.Int8Reader().read(bc, offset));
}

class FloatVector {
  FloatVector._(this._bc, this._bcOffset);

  static const fb.Reader<FloatVector> reader = _FloatVectorReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  double get x => const fb.Float32Reader().read(_bc, _bcOffset + 0);
  double get y => const fb.Float32Reader().read(_bc, _bcOffset + 4);
  double get z => const fb.Float32Reader().read(_bc, _bcOffset + 8);

  @override
  String toString() {
    return 'FloatVector{x: ${x}, y: ${y}, z: ${z}}';
  }
}

class _FloatVectorReader extends fb.StructReader<FloatVector> {
  const _FloatVectorReader();

  @override
  int get size => 12;

  @override
  FloatVector createObject(fb.BufferContext bc, int offset) => 
    FloatVector._(bc, offset);
}

class FloatVectorBuilder {
  FloatVectorBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(double x, double y, double z) {
    fbBuilder.putFloat32(z);
    fbBuilder.putFloat32(y);
    fbBuilder.putFloat32(x);
    return fbBuilder.offset;
  }

}

class FloatVectorObjectBuilder extends fb.ObjectBuilder {
  final double _x;
  final double _y;
  final double _z;

  FloatVectorObjectBuilder({
    required double x,
    required double y,
    required double z,
  })
      : _x = x,
        _y = y,
        _z = z;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.putFloat32(_z);
    fbBuilder.putFloat32(_y);
    fbBuilder.putFloat32(_x);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class DoubleVector {
  DoubleVector._(this._bc, this._bcOffset);

  static const fb.Reader<DoubleVector> reader = _DoubleVectorReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  double get x => const fb.Float64Reader().read(_bc, _bcOffset + 0);
  double get y => const fb.Float64Reader().read(_bc, _bcOffset + 8);
  double get z => const fb.Float64Reader().read(_bc, _bcOffset + 16);

  @override
  String toString() {
    return 'DoubleVector{x: ${x}, y: ${y}, z: ${z}}';
  }
}

class _DoubleVectorReader extends fb.StructReader<DoubleVector> {
  const _DoubleVectorReader();

  @override
  int get size => 24;

  @override
  DoubleVector createObject(fb.BufferContext bc, int offset) => 
    DoubleVector._(bc, offset);
}

class DoubleVectorBuilder {
  DoubleVectorBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(double x, double y, double z) {
    fbBuilder.putFloat64(z);
    fbBuilder.putFloat64(y);
    fbBuilder.putFloat64(x);
    return fbBuilder.offset;
  }

}

class DoubleVectorObjectBuilder extends fb.ObjectBuilder {
  final double _x;
  final double _y;
  final double _z;

  DoubleVectorObjectBuilder({
    required double x,
    required double y,
    required double z,
  })
      : _x = x,
        _y = y,
        _z = z;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.putFloat64(_z);
    fbBuilder.putFloat64(_y);
    fbBuilder.putFloat64(_x);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Transform {
  Transform._(this._bc, this._bcOffset);

  static const fb.Reader<Transform> reader = _TransformReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  DoubleVector get position => DoubleVector.reader.read(_bc, _bcOffset + 0);
  FloatVector get xDirection => FloatVector.reader.read(_bc, _bcOffset + 24);
  FloatVector get yDirection => FloatVector.reader.read(_bc, _bcOffset + 36);

  @override
  String toString() {
    return 'Transform{position: ${position}, xDirection: ${xDirection}, yDirection: ${yDirection}}';
  }
}

class _TransformReader extends fb.StructReader<Transform> {
  const _TransformReader();

  @override
  int get size => 48;

  @override
  Transform createObject(fb.BufferContext bc, int offset) => 
    Transform._(bc, offset);
}

class TransformBuilder {
  TransformBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(fb.StructBuilder position, fb.StructBuilder xDirection, fb.StructBuilder yDirection) {
    yDirection();
    xDirection();
    position();
    return fbBuilder.offset;
  }

}

class TransformObjectBuilder extends fb.ObjectBuilder {
  final DoubleVectorObjectBuilder _position;
  final FloatVectorObjectBuilder _xDirection;
  final FloatVectorObjectBuilder _yDirection;

  TransformObjectBuilder({
    required DoubleVectorObjectBuilder position,
    required FloatVectorObjectBuilder xDirection,
    required FloatVectorObjectBuilder yDirection,
  })
      : _position = position,
        _xDirection = xDirection,
        _yDirection = yDirection;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    _yDirection.finish(fbBuilder);
    _xDirection.finish(fbBuilder);
    _position.finish(fbBuilder);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Material {
  Material._(this._bc, this._bcOffset);

  static const fb.Reader<Material> reader = _MaterialReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get r => const fb.Uint8Reader().read(_bc, _bcOffset + 0);
  int get g => const fb.Uint8Reader().read(_bc, _bcOffset + 1);
  int get b => const fb.Uint8Reader().read(_bc, _bcOffset + 2);
  int get a => const fb.Uint8Reader().read(_bc, _bcOffset + 3);
  RenderedFaces get renderedFaces => RenderedFaces.fromValue(const fb.Int8Reader().read(_bc, _bcOffset + 4));
  Stroke get stroke => Stroke.fromValue(const fb.Int8Reader().read(_bc, _bcOffset + 5));

  @override
  String toString() {
    return 'Material{r: ${r}, g: ${g}, b: ${b}, a: ${a}, renderedFaces: ${renderedFaces}, stroke: ${stroke}}';
  }
}

class _MaterialReader extends fb.StructReader<Material> {
  const _MaterialReader();

  @override
  int get size => 6;

  @override
  Material createObject(fb.BufferContext bc, int offset) => 
    Material._(bc, offset);
}

class MaterialBuilder {
  MaterialBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(int r, int g, int b, int a, RenderedFaces renderedFaces, Stroke stroke) {
    fbBuilder.putInt8(stroke.value);
    fbBuilder.putInt8(renderedFaces.value);
    fbBuilder.putUint8(a);
    fbBuilder.putUint8(b);
    fbBuilder.putUint8(g);
    fbBuilder.putUint8(r);
    return fbBuilder.offset;
  }

}

class MaterialObjectBuilder extends fb.ObjectBuilder {
  final int _r;
  final int _g;
  final int _b;
  final int _a;
  final RenderedFaces _renderedFaces;
  final Stroke _stroke;

  MaterialObjectBuilder({
    required int r,
    required int g,
    required int b,
    required int a,
    required RenderedFaces renderedFaces,
    required Stroke stroke,
  })
      : _r = r,
        _g = g,
        _b = b,
        _a = a,
        _renderedFaces = renderedFaces,
        _stroke = stroke;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.putInt8(_stroke.value);
    fbBuilder.putInt8(_renderedFaces.value);
    fbBuilder.putUint8(_a);
    fbBuilder.putUint8(_b);
    fbBuilder.putUint8(_g);
    fbBuilder.putUint8(_r);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class BoundingBox {
  BoundingBox._(this._bc, this._bcOffset);

  static const fb.Reader<BoundingBox> reader = _BoundingBoxReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  FloatVector get min => FloatVector.reader.read(_bc, _bcOffset + 0);
  FloatVector get max => FloatVector.reader.read(_bc, _bcOffset + 12);

  @override
  String toString() {
    return 'BoundingBox{min: ${min}, max: ${max}}';
  }
}

class _BoundingBoxReader extends fb.StructReader<BoundingBox> {
  const _BoundingBoxReader();

  @override
  int get size => 24;

  @override
  BoundingBox createObject(fb.BufferContext bc, int offset) => 
    BoundingBox._(bc, offset);
}

class BoundingBoxBuilder {
  BoundingBoxBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(fb.StructBuilder min, fb.StructBuilder max) {
    max();
    min();
    return fbBuilder.offset;
  }

}

class BoundingBoxObjectBuilder extends fb.ObjectBuilder {
  final FloatVectorObjectBuilder _min;
  final FloatVectorObjectBuilder _max;

  BoundingBoxObjectBuilder({
    required FloatVectorObjectBuilder min,
    required FloatVectorObjectBuilder max,
  })
      : _min = min,
        _max = max;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    _max.finish(fbBuilder);
    _min.finish(fbBuilder);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Wire {
  Wire._(this._bc, this._bcOffset);

  static const fb.Reader<Wire> reader = _WireReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  FloatVector get p1 => FloatVector.reader.read(_bc, _bcOffset + 0);
  FloatVector get p2 => FloatVector.reader.read(_bc, _bcOffset + 12);

  @override
  String toString() {
    return 'Wire{p1: ${p1}, p2: ${p2}}';
  }
}

class _WireReader extends fb.StructReader<Wire> {
  const _WireReader();

  @override
  int get size => 24;

  @override
  Wire createObject(fb.BufferContext bc, int offset) => 
    Wire._(bc, offset);
}

class WireBuilder {
  WireBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(fb.StructBuilder p1, fb.StructBuilder p2) {
    p2();
    p1();
    return fbBuilder.offset;
  }

}

class WireObjectBuilder extends fb.ObjectBuilder {
  final FloatVectorObjectBuilder _p1;
  final FloatVectorObjectBuilder _p2;

  WireObjectBuilder({
    required FloatVectorObjectBuilder p1,
    required FloatVectorObjectBuilder p2,
  })
      : _p1 = p1,
        _p2 = p2;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    _p2.finish(fbBuilder);
    _p1.finish(fbBuilder);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class WireSet {
  WireSet._(this._bc, this._bcOffset);
  factory WireSet(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<WireSet> reader = _WireSetReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<FloatVector>? get ps => const fb.ListReader<FloatVector>(FloatVector.reader).vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'WireSet{ps: ${ps}}';
  }
}

class _WireSetReader extends fb.TableReader<WireSet> {
  const _WireSetReader();

  @override
  WireSet createObject(fb.BufferContext bc, int offset) => 
    WireSet._(bc, offset);
}

class WireSetBuilder {
  WireSetBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addPsOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class WireSetObjectBuilder extends fb.ObjectBuilder {
  final List<FloatVectorObjectBuilder>? _ps;

  WireSetObjectBuilder({
    List<FloatVectorObjectBuilder>? ps,
  })
      : _ps = ps;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? psOffset = _ps == null ? null
        : fbBuilder.writeListOfStructs(_ps!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, psOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class CircleCurve {
  CircleCurve._(this._bc, this._bcOffset);

  static const fb.Reader<CircleCurve> reader = _CircleCurveReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  double get aperture => const fb.Float32Reader().read(_bc, _bcOffset + 0);
  FloatVector get position => FloatVector.reader.read(_bc, _bcOffset + 4);
  double get radius => const fb.Float32Reader().read(_bc, _bcOffset + 16);
  FloatVector get xDirection => FloatVector.reader.read(_bc, _bcOffset + 20);
  FloatVector get yDirection => FloatVector.reader.read(_bc, _bcOffset + 32);

  @override
  String toString() {
    return 'CircleCurve{aperture: ${aperture}, position: ${position}, radius: ${radius}, xDirection: ${xDirection}, yDirection: ${yDirection}}';
  }
}

class _CircleCurveReader extends fb.StructReader<CircleCurve> {
  const _CircleCurveReader();

  @override
  int get size => 44;

  @override
  CircleCurve createObject(fb.BufferContext bc, int offset) => 
    CircleCurve._(bc, offset);
}

class CircleCurveBuilder {
  CircleCurveBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(double aperture, fb.StructBuilder position, double radius, fb.StructBuilder xDirection, fb.StructBuilder yDirection) {
    yDirection();
    xDirection();
    fbBuilder.putFloat32(radius);
    position();
    fbBuilder.putFloat32(aperture);
    return fbBuilder.offset;
  }

}

class CircleCurveObjectBuilder extends fb.ObjectBuilder {
  final double _aperture;
  final FloatVectorObjectBuilder _position;
  final double _radius;
  final FloatVectorObjectBuilder _xDirection;
  final FloatVectorObjectBuilder _yDirection;

  CircleCurveObjectBuilder({
    required double aperture,
    required FloatVectorObjectBuilder position,
    required double radius,
    required FloatVectorObjectBuilder xDirection,
    required FloatVectorObjectBuilder yDirection,
  })
      : _aperture = aperture,
        _position = position,
        _radius = radius,
        _xDirection = xDirection,
        _yDirection = yDirection;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    _yDirection.finish(fbBuilder);
    _xDirection.finish(fbBuilder);
    fbBuilder.putFloat32(_radius);
    _position.finish(fbBuilder);
    fbBuilder.putFloat32(_aperture);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class ShellHole {
  ShellHole._(this._bc, this._bcOffset);
  factory ShellHole(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ShellHole> reader = _ShellHoleReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<int>? get indices => const fb.ListReader<int>(fb.Uint16Reader()).vTableGetNullable(_bc, _bcOffset, 4);
  int get profileId => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 6, 0);

  @override
  String toString() {
    return 'ShellHole{indices: ${indices}, profileId: ${profileId}}';
  }
}

class _ShellHoleReader extends fb.TableReader<ShellHole> {
  const _ShellHoleReader();

  @override
  ShellHole createObject(fb.BufferContext bc, int offset) => 
    ShellHole._(bc, offset);
}

class ShellHoleBuilder {
  ShellHoleBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addIndicesOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addProfileId(int? profileId) {
    fbBuilder.addUint16(1, profileId);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ShellHoleObjectBuilder extends fb.ObjectBuilder {
  final List<int>? _indices;
  final int? _profileId;

  ShellHoleObjectBuilder({
    List<int>? indices,
    int? profileId,
  })
      : _indices = indices,
        _profileId = profileId;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? indicesOffset = _indices == null ? null
        : fbBuilder.writeListUint16(_indices!);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, indicesOffset);
    fbBuilder.addUint16(1, _profileId);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class ShellProfile {
  ShellProfile._(this._bc, this._bcOffset);
  factory ShellProfile(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ShellProfile> reader = _ShellProfileReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<int>? get indices => const fb.ListReader<int>(fb.Uint16Reader()).vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'ShellProfile{indices: ${indices}}';
  }
}

class _ShellProfileReader extends fb.TableReader<ShellProfile> {
  const _ShellProfileReader();

  @override
  ShellProfile createObject(fb.BufferContext bc, int offset) => 
    ShellProfile._(bc, offset);
}

class ShellProfileBuilder {
  ShellProfileBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addIndicesOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ShellProfileObjectBuilder extends fb.ObjectBuilder {
  final List<int>? _indices;

  ShellProfileObjectBuilder({
    List<int>? indices,
  })
      : _indices = indices;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? indicesOffset = _indices == null ? null
        : fbBuilder.writeListUint16(_indices!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, indicesOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class BigShellHole {
  BigShellHole._(this._bc, this._bcOffset);
  factory BigShellHole(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<BigShellHole> reader = _BigShellHoleReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<int>? get indices => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 4);
  int get profileId => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 6, 0);

  @override
  String toString() {
    return 'BigShellHole{indices: ${indices}, profileId: ${profileId}}';
  }
}

class _BigShellHoleReader extends fb.TableReader<BigShellHole> {
  const _BigShellHoleReader();

  @override
  BigShellHole createObject(fb.BufferContext bc, int offset) => 
    BigShellHole._(bc, offset);
}

class BigShellHoleBuilder {
  BigShellHoleBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addIndicesOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addProfileId(int? profileId) {
    fbBuilder.addUint16(1, profileId);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class BigShellHoleObjectBuilder extends fb.ObjectBuilder {
  final List<int>? _indices;
  final int? _profileId;

  BigShellHoleObjectBuilder({
    List<int>? indices,
    int? profileId,
  })
      : _indices = indices,
        _profileId = profileId;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? indicesOffset = _indices == null ? null
        : fbBuilder.writeListUint32(_indices!);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, indicesOffset);
    fbBuilder.addUint16(1, _profileId);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class BigShellProfile {
  BigShellProfile._(this._bc, this._bcOffset);
  factory BigShellProfile(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<BigShellProfile> reader = _BigShellProfileReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<int>? get indices => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'BigShellProfile{indices: ${indices}}';
  }
}

class _BigShellProfileReader extends fb.TableReader<BigShellProfile> {
  const _BigShellProfileReader();

  @override
  BigShellProfile createObject(fb.BufferContext bc, int offset) => 
    BigShellProfile._(bc, offset);
}

class BigShellProfileBuilder {
  BigShellProfileBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addIndicesOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class BigShellProfileObjectBuilder extends fb.ObjectBuilder {
  final List<int>? _indices;

  BigShellProfileObjectBuilder({
    List<int>? indices,
  })
      : _indices = indices;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? indicesOffset = _indices == null ? null
        : fbBuilder.writeListUint32(_indices!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, indicesOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Axis {
  Axis._(this._bc, this._bcOffset);
  factory Axis(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Axis> reader = _AxisReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<Wire>? get wires => const fb.ListReader<Wire>(Wire.reader).vTableGetNullable(_bc, _bcOffset, 4);
  List<int>? get order => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 6);
  List<AxisPartClass>? get parts => const fb.ListReader<AxisPartClass>(AxisPartClass.reader).vTableGetNullable(_bc, _bcOffset, 8);
  List<WireSet>? get wireSets => const fb.ListReader<WireSet>(WireSet.reader).vTableGetNullable(_bc, _bcOffset, 10);
  List<CircleCurve>? get circleCurves => const fb.ListReader<CircleCurve>(CircleCurve.reader).vTableGetNullable(_bc, _bcOffset, 12);

  @override
  String toString() {
    return 'Axis{wires: ${wires}, order: ${order}, parts: ${parts}, wireSets: ${wireSets}, circleCurves: ${circleCurves}}';
  }
}

class _AxisReader extends fb.TableReader<Axis> {
  const _AxisReader();

  @override
  Axis createObject(fb.BufferContext bc, int offset) => 
    Axis._(bc, offset);
}

class AxisBuilder {
  AxisBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(5);
  }

  int addWiresOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addOrderOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addPartsOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addWireSetsOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }
  int addCircleCurvesOffset(int? offset) {
    fbBuilder.addOffset(4, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class AxisObjectBuilder extends fb.ObjectBuilder {
  final List<WireObjectBuilder>? _wires;
  final List<int>? _order;
  final List<AxisPartClass>? _parts;
  final List<WireSetObjectBuilder>? _wireSets;
  final List<CircleCurveObjectBuilder>? _circleCurves;

  AxisObjectBuilder({
    List<WireObjectBuilder>? wires,
    List<int>? order,
    List<AxisPartClass>? parts,
    List<WireSetObjectBuilder>? wireSets,
    List<CircleCurveObjectBuilder>? circleCurves,
  })
      : _wires = wires,
        _order = order,
        _parts = parts,
        _wireSets = wireSets,
        _circleCurves = circleCurves;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? wiresOffset = _wires == null ? null
        : fbBuilder.writeListOfStructs(_wires!);
    final int? orderOffset = _order == null ? null
        : fbBuilder.writeListUint32(_order!);
    final int? partsOffset = _parts == null ? null
        : fbBuilder.writeListInt8(_parts!.map((f) => f.value).toList());
    final int? wireSetsOffset = _wireSets == null ? null
        : fbBuilder.writeList(_wireSets!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? circleCurvesOffset = _circleCurves == null ? null
        : fbBuilder.writeListOfStructs(_circleCurves!);
    fbBuilder.startTable(5);
    fbBuilder.addOffset(0, wiresOffset);
    fbBuilder.addOffset(1, orderOffset);
    fbBuilder.addOffset(2, partsOffset);
    fbBuilder.addOffset(3, wireSetsOffset);
    fbBuilder.addOffset(4, circleCurvesOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Representation {
  Representation._(this._bc, this._bcOffset);

  static const fb.Reader<Representation> reader = _RepresentationReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get id => const fb.Uint32Reader().read(_bc, _bcOffset + 0);
  BoundingBox get bbox => BoundingBox.reader.read(_bc, _bcOffset + 4);
  RepresentationClass get representationClass => RepresentationClass.fromValue(const fb.Int8Reader().read(_bc, _bcOffset + 28));

  @override
  String toString() {
    return 'Representation{id: ${id}, bbox: ${bbox}, representationClass: ${representationClass}}';
  }
}

class _RepresentationReader extends fb.StructReader<Representation> {
  const _RepresentationReader();

  @override
  int get size => 32;

  @override
  Representation createObject(fb.BufferContext bc, int offset) => 
    Representation._(bc, offset);
}

class RepresentationBuilder {
  RepresentationBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(int id, fb.StructBuilder bbox, RepresentationClass representationClass) {
    fbBuilder.pad(3);
    fbBuilder.putInt8(representationClass.value);
    bbox();
    fbBuilder.putUint32(id);
    return fbBuilder.offset;
  }

}

class RepresentationObjectBuilder extends fb.ObjectBuilder {
  final int _id;
  final BoundingBoxObjectBuilder _bbox;
  final RepresentationClass _representationClass;

  RepresentationObjectBuilder({
    required int id,
    required BoundingBoxObjectBuilder bbox,
    required RepresentationClass representationClass,
  })
      : _id = id,
        _bbox = bbox,
        _representationClass = representationClass;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.pad(3);
    fbBuilder.putInt8(_representationClass.value);
    _bbox.finish(fbBuilder);
    fbBuilder.putUint32(_id);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Sample {
  Sample._(this._bc, this._bcOffset);

  static const fb.Reader<Sample> reader = _SampleReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get item => const fb.Uint32Reader().read(_bc, _bcOffset + 0);
  int get material => const fb.Uint32Reader().read(_bc, _bcOffset + 4);
  int get representation => const fb.Uint32Reader().read(_bc, _bcOffset + 8);
  int get localTransform => const fb.Uint32Reader().read(_bc, _bcOffset + 12);

  @override
  String toString() {
    return 'Sample{item: ${item}, material: ${material}, representation: ${representation}, localTransform: ${localTransform}}';
  }
}

class _SampleReader extends fb.StructReader<Sample> {
  const _SampleReader();

  @override
  int get size => 16;

  @override
  Sample createObject(fb.BufferContext bc, int offset) => 
    Sample._(bc, offset);
}

class SampleBuilder {
  SampleBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(int item, int material, int representation, int localTransform) {
    fbBuilder.putUint32(localTransform);
    fbBuilder.putUint32(representation);
    fbBuilder.putUint32(material);
    fbBuilder.putUint32(item);
    return fbBuilder.offset;
  }

}

class SampleObjectBuilder extends fb.ObjectBuilder {
  final int _item;
  final int _material;
  final int _representation;
  final int _localTransform;

  SampleObjectBuilder({
    required int item,
    required int material,
    required int representation,
    required int localTransform,
  })
      : _item = item,
        _material = material,
        _representation = representation,
        _localTransform = localTransform;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.putUint32(_localTransform);
    fbBuilder.putUint32(_representation);
    fbBuilder.putUint32(_material);
    fbBuilder.putUint32(_item);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Shell {
  Shell._(this._bc, this._bcOffset);
  factory Shell(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Shell> reader = _ShellReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<ShellProfile>? get profiles => const fb.ListReader<ShellProfile>(ShellProfile.reader).vTableGetNullable(_bc, _bcOffset, 4);
  List<ShellHole>? get holes => const fb.ListReader<ShellHole>(ShellHole.reader).vTableGetNullable(_bc, _bcOffset, 6);
  List<FloatVector>? get points => const fb.ListReader<FloatVector>(FloatVector.reader).vTableGetNullable(_bc, _bcOffset, 8);
  List<BigShellProfile>? get bigProfiles => const fb.ListReader<BigShellProfile>(BigShellProfile.reader).vTableGetNullable(_bc, _bcOffset, 10);
  List<BigShellHole>? get bigHoles => const fb.ListReader<BigShellHole>(BigShellHole.reader).vTableGetNullable(_bc, _bcOffset, 12);
  ShellType get type => ShellType.fromValue(const fb.Int8Reader().vTableGet(_bc, _bcOffset, 14, 0));
  List<int>? get profilesFaceIds => const fb.ListReader<int>(fb.Uint16Reader()).vTableGetNullable(_bc, _bcOffset, 16);

  @override
  String toString() {
    return 'Shell{profiles: ${profiles}, holes: ${holes}, points: ${points}, bigProfiles: ${bigProfiles}, bigHoles: ${bigHoles}, type: ${type}, profilesFaceIds: ${profilesFaceIds}}';
  }
}

class _ShellReader extends fb.TableReader<Shell> {
  const _ShellReader();

  @override
  Shell createObject(fb.BufferContext bc, int offset) => 
    Shell._(bc, offset);
}

class ShellBuilder {
  ShellBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(7);
  }

  int addProfilesOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addHolesOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addPointsOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addBigProfilesOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }
  int addBigHolesOffset(int? offset) {
    fbBuilder.addOffset(4, offset);
    return fbBuilder.offset;
  }
  int addType(ShellType? type) {
    fbBuilder.addInt8(5, type?.value);
    return fbBuilder.offset;
  }
  int addProfilesFaceIdsOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ShellObjectBuilder extends fb.ObjectBuilder {
  final List<ShellProfileObjectBuilder>? _profiles;
  final List<ShellHoleObjectBuilder>? _holes;
  final List<FloatVectorObjectBuilder>? _points;
  final List<BigShellProfileObjectBuilder>? _bigProfiles;
  final List<BigShellHoleObjectBuilder>? _bigHoles;
  final ShellType? _type;
  final List<int>? _profilesFaceIds;

  ShellObjectBuilder({
    List<ShellProfileObjectBuilder>? profiles,
    List<ShellHoleObjectBuilder>? holes,
    List<FloatVectorObjectBuilder>? points,
    List<BigShellProfileObjectBuilder>? bigProfiles,
    List<BigShellHoleObjectBuilder>? bigHoles,
    ShellType? type,
    List<int>? profilesFaceIds,
  })
      : _profiles = profiles,
        _holes = holes,
        _points = points,
        _bigProfiles = bigProfiles,
        _bigHoles = bigHoles,
        _type = type,
        _profilesFaceIds = profilesFaceIds;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? profilesOffset = _profiles == null ? null
        : fbBuilder.writeList(_profiles!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? holesOffset = _holes == null ? null
        : fbBuilder.writeList(_holes!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? pointsOffset = _points == null ? null
        : fbBuilder.writeListOfStructs(_points!);
    final int? bigProfilesOffset = _bigProfiles == null ? null
        : fbBuilder.writeList(_bigProfiles!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? bigHolesOffset = _bigHoles == null ? null
        : fbBuilder.writeList(_bigHoles!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? profilesFaceIdsOffset = _profilesFaceIds == null ? null
        : fbBuilder.writeListUint16(_profilesFaceIds!);
    fbBuilder.startTable(7);
    fbBuilder.addOffset(0, profilesOffset);
    fbBuilder.addOffset(1, holesOffset);
    fbBuilder.addOffset(2, pointsOffset);
    fbBuilder.addOffset(3, bigProfilesOffset);
    fbBuilder.addOffset(4, bigHolesOffset);
    fbBuilder.addInt8(5, _type?.value);
    fbBuilder.addOffset(6, profilesFaceIdsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class CircleExtrusion {
  CircleExtrusion._(this._bc, this._bcOffset);
  factory CircleExtrusion(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<CircleExtrusion> reader = _CircleExtrusionReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<double>? get radius => const fb.ListReader<double>(fb.Float64Reader()).vTableGetNullable(_bc, _bcOffset, 4);
  List<Axis>? get axes => const fb.ListReader<Axis>(Axis.reader).vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'CircleExtrusion{radius: ${radius}, axes: ${axes}}';
  }
}

class _CircleExtrusionReader extends fb.TableReader<CircleExtrusion> {
  const _CircleExtrusionReader();

  @override
  CircleExtrusion createObject(fb.BufferContext bc, int offset) => 
    CircleExtrusion._(bc, offset);
}

class CircleExtrusionBuilder {
  CircleExtrusionBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addRadiusOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addAxesOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class CircleExtrusionObjectBuilder extends fb.ObjectBuilder {
  final List<double>? _radius;
  final List<AxisObjectBuilder>? _axes;

  CircleExtrusionObjectBuilder({
    List<double>? radius,
    List<AxisObjectBuilder>? axes,
  })
      : _radius = radius,
        _axes = axes;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? radiusOffset = _radius == null ? null
        : fbBuilder.writeListFloat64(_radius!);
    final int? axesOffset = _axes == null ? null
        : fbBuilder.writeList(_axes!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, radiusOffset);
    fbBuilder.addOffset(1, axesOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Meshes {
  Meshes._(this._bc, this._bcOffset);
  factory Meshes(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Meshes> reader = _MeshesReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  Transform? get coordinates => Transform.reader.vTableGetNullable(_bc, _bcOffset, 4);
  List<int>? get meshesItems => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 6);
  List<Sample>? get samples => const fb.ListReader<Sample>(Sample.reader).vTableGetNullable(_bc, _bcOffset, 8);
  List<Representation>? get representations => const fb.ListReader<Representation>(Representation.reader).vTableGetNullable(_bc, _bcOffset, 10);
  List<Material>? get materials => const fb.ListReader<Material>(Material.reader).vTableGetNullable(_bc, _bcOffset, 12);
  List<CircleExtrusion>? get circleExtrusions => const fb.ListReader<CircleExtrusion>(CircleExtrusion.reader).vTableGetNullable(_bc, _bcOffset, 14);
  List<Shell>? get shells => const fb.ListReader<Shell>(Shell.reader).vTableGetNullable(_bc, _bcOffset, 16);
  List<Transform>? get localTransforms => const fb.ListReader<Transform>(Transform.reader).vTableGetNullable(_bc, _bcOffset, 18);
  List<Transform>? get globalTransforms => const fb.ListReader<Transform>(Transform.reader).vTableGetNullable(_bc, _bcOffset, 20);
  List<int>? get materialIds => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 22);
  List<int>? get representationIds => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 24);
  List<int>? get sampleIds => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 26);
  List<int>? get localTransformIds => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 28);
  List<int>? get globalTransformIds => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 30);

  @override
  String toString() {
    return 'Meshes{coordinates: ${coordinates}, meshesItems: ${meshesItems}, samples: ${samples}, representations: ${representations}, materials: ${materials}, circleExtrusions: ${circleExtrusions}, shells: ${shells}, localTransforms: ${localTransforms}, globalTransforms: ${globalTransforms}, materialIds: ${materialIds}, representationIds: ${representationIds}, sampleIds: ${sampleIds}, localTransformIds: ${localTransformIds}, globalTransformIds: ${globalTransformIds}}';
  }
}

class _MeshesReader extends fb.TableReader<Meshes> {
  const _MeshesReader();

  @override
  Meshes createObject(fb.BufferContext bc, int offset) => 
    Meshes._(bc, offset);
}

class MeshesBuilder {
  MeshesBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(14);
  }

  int addCoordinates(int offset) {
    fbBuilder.addStruct(0, offset);
    return fbBuilder.offset;
  }
  int addMeshesItemsOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addSamplesOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addRepresentationsOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }
  int addMaterialsOffset(int? offset) {
    fbBuilder.addOffset(4, offset);
    return fbBuilder.offset;
  }
  int addCircleExtrusionsOffset(int? offset) {
    fbBuilder.addOffset(5, offset);
    return fbBuilder.offset;
  }
  int addShellsOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }
  int addLocalTransformsOffset(int? offset) {
    fbBuilder.addOffset(7, offset);
    return fbBuilder.offset;
  }
  int addGlobalTransformsOffset(int? offset) {
    fbBuilder.addOffset(8, offset);
    return fbBuilder.offset;
  }
  int addMaterialIdsOffset(int? offset) {
    fbBuilder.addOffset(9, offset);
    return fbBuilder.offset;
  }
  int addRepresentationIdsOffset(int? offset) {
    fbBuilder.addOffset(10, offset);
    return fbBuilder.offset;
  }
  int addSampleIdsOffset(int? offset) {
    fbBuilder.addOffset(11, offset);
    return fbBuilder.offset;
  }
  int addLocalTransformIdsOffset(int? offset) {
    fbBuilder.addOffset(12, offset);
    return fbBuilder.offset;
  }
  int addGlobalTransformIdsOffset(int? offset) {
    fbBuilder.addOffset(13, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class MeshesObjectBuilder extends fb.ObjectBuilder {
  final TransformObjectBuilder? _coordinates;
  final List<int>? _meshesItems;
  final List<SampleObjectBuilder>? _samples;
  final List<RepresentationObjectBuilder>? _representations;
  final List<MaterialObjectBuilder>? _materials;
  final List<CircleExtrusionObjectBuilder>? _circleExtrusions;
  final List<ShellObjectBuilder>? _shells;
  final List<TransformObjectBuilder>? _localTransforms;
  final List<TransformObjectBuilder>? _globalTransforms;
  final List<int>? _materialIds;
  final List<int>? _representationIds;
  final List<int>? _sampleIds;
  final List<int>? _localTransformIds;
  final List<int>? _globalTransformIds;

  MeshesObjectBuilder({
    TransformObjectBuilder? coordinates,
    List<int>? meshesItems,
    List<SampleObjectBuilder>? samples,
    List<RepresentationObjectBuilder>? representations,
    List<MaterialObjectBuilder>? materials,
    List<CircleExtrusionObjectBuilder>? circleExtrusions,
    List<ShellObjectBuilder>? shells,
    List<TransformObjectBuilder>? localTransforms,
    List<TransformObjectBuilder>? globalTransforms,
    List<int>? materialIds,
    List<int>? representationIds,
    List<int>? sampleIds,
    List<int>? localTransformIds,
    List<int>? globalTransformIds,
  })
      : _coordinates = coordinates,
        _meshesItems = meshesItems,
        _samples = samples,
        _representations = representations,
        _materials = materials,
        _circleExtrusions = circleExtrusions,
        _shells = shells,
        _localTransforms = localTransforms,
        _globalTransforms = globalTransforms,
        _materialIds = materialIds,
        _representationIds = representationIds,
        _sampleIds = sampleIds,
        _localTransformIds = localTransformIds,
        _globalTransformIds = globalTransformIds;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? meshesItemsOffset = _meshesItems == null ? null
        : fbBuilder.writeListUint32(_meshesItems!);
    final int? samplesOffset = _samples == null ? null
        : fbBuilder.writeListOfStructs(_samples!);
    final int? representationsOffset = _representations == null ? null
        : fbBuilder.writeListOfStructs(_representations!);
    final int? materialsOffset = _materials == null ? null
        : fbBuilder.writeListOfStructs(_materials!);
    final int? circleExtrusionsOffset = _circleExtrusions == null ? null
        : fbBuilder.writeList(_circleExtrusions!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? shellsOffset = _shells == null ? null
        : fbBuilder.writeList(_shells!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? localTransformsOffset = _localTransforms == null ? null
        : fbBuilder.writeListOfStructs(_localTransforms!);
    final int? globalTransformsOffset = _globalTransforms == null ? null
        : fbBuilder.writeListOfStructs(_globalTransforms!);
    final int? materialIdsOffset = _materialIds == null ? null
        : fbBuilder.writeListUint32(_materialIds!);
    final int? representationIdsOffset = _representationIds == null ? null
        : fbBuilder.writeListUint32(_representationIds!);
    final int? sampleIdsOffset = _sampleIds == null ? null
        : fbBuilder.writeListUint32(_sampleIds!);
    final int? localTransformIdsOffset = _localTransformIds == null ? null
        : fbBuilder.writeListUint32(_localTransformIds!);
    final int? globalTransformIdsOffset = _globalTransformIds == null ? null
        : fbBuilder.writeListUint32(_globalTransformIds!);
    fbBuilder.startTable(14);
    if (_coordinates != null) {
      fbBuilder.addStruct(0, _coordinates!.finish(fbBuilder));
    }
    fbBuilder.addOffset(1, meshesItemsOffset);
    fbBuilder.addOffset(2, samplesOffset);
    fbBuilder.addOffset(3, representationsOffset);
    fbBuilder.addOffset(4, materialsOffset);
    fbBuilder.addOffset(5, circleExtrusionsOffset);
    fbBuilder.addOffset(6, shellsOffset);
    fbBuilder.addOffset(7, localTransformsOffset);
    fbBuilder.addOffset(8, globalTransformsOffset);
    fbBuilder.addOffset(9, materialIdsOffset);
    fbBuilder.addOffset(10, representationIdsOffset);
    fbBuilder.addOffset(11, sampleIdsOffset);
    fbBuilder.addOffset(12, localTransformIdsOffset);
    fbBuilder.addOffset(13, globalTransformIdsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Attribute {
  Attribute._(this._bc, this._bcOffset);
  factory Attribute(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Attribute> reader = _AttributeReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<String>? get data => const fb.ListReader<String>(fb.StringReader()).vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'Attribute{data: ${data}}';
  }
}

class _AttributeReader extends fb.TableReader<Attribute> {
  const _AttributeReader();

  @override
  Attribute createObject(fb.BufferContext bc, int offset) => 
    Attribute._(bc, offset);
}

class AttributeBuilder {
  AttributeBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addDataOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class AttributeObjectBuilder extends fb.ObjectBuilder {
  final List<String>? _data;

  AttributeObjectBuilder({
    List<String>? data,
  })
      : _data = data;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? dataOffset = _data == null ? null
        : fbBuilder.writeList(_data!.map(fbBuilder.writeString).toList());
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, dataOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Relation {
  Relation._(this._bc, this._bcOffset);
  factory Relation(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Relation> reader = _RelationReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<String>? get data => const fb.ListReader<String>(fb.StringReader()).vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'Relation{data: ${data}}';
  }
}

class _RelationReader extends fb.TableReader<Relation> {
  const _RelationReader();

  @override
  Relation createObject(fb.BufferContext bc, int offset) => 
    Relation._(bc, offset);
}

class RelationBuilder {
  RelationBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addDataOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class RelationObjectBuilder extends fb.ObjectBuilder {
  final List<String>? _data;

  RelationObjectBuilder({
    List<String>? data,
  })
      : _data = data;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? dataOffset = _data == null ? null
        : fbBuilder.writeList(_data!.map(fbBuilder.writeString).toList());
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, dataOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class SpatialStructure {
  SpatialStructure._(this._bc, this._bcOffset);
  factory SpatialStructure(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<SpatialStructure> reader = _SpatialStructureReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get localId => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  String? get category => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  List<SpatialStructure>? get children => const fb.ListReader<SpatialStructure>(SpatialStructure.reader).vTableGetNullable(_bc, _bcOffset, 8);

  @override
  String toString() {
    return 'SpatialStructure{localId: ${localId}, category: ${category}, children: ${children}}';
  }
}

class _SpatialStructureReader extends fb.TableReader<SpatialStructure> {
  const _SpatialStructureReader();

  @override
  SpatialStructure createObject(fb.BufferContext bc, int offset) => 
    SpatialStructure._(bc, offset);
}

class SpatialStructureBuilder {
  SpatialStructureBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addLocalId(int? localId) {
    fbBuilder.addUint32(0, localId);
    return fbBuilder.offset;
  }
  int addCategoryOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addChildrenOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class SpatialStructureObjectBuilder extends fb.ObjectBuilder {
  final int? _localId;
  final String? _category;
  final List<SpatialStructureObjectBuilder>? _children;

  SpatialStructureObjectBuilder({
    int? localId,
    String? category,
    List<SpatialStructureObjectBuilder>? children,
  })
      : _localId = localId,
        _category = category,
        _children = children;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? categoryOffset = _category == null ? null
        : fbBuilder.writeString(_category!);
    final int? childrenOffset = _children == null ? null
        : fbBuilder.writeList(_children!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(3);
    fbBuilder.addUint32(0, _localId);
    fbBuilder.addOffset(1, categoryOffset);
    fbBuilder.addOffset(2, childrenOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class ModelIndex {
  ModelIndex._(this._bc, this._bcOffset);
  factory ModelIndex(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ModelIndex> reader = _ModelIndexReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get name => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  List<String>? get stringKeys => const fb.ListReader<String>(fb.StringReader()).vTableGetNullable(_bc, _bcOffset, 6);
  List<int>? get numberKeys => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 8);
  List<String>? get stringValues => const fb.ListReader<String>(fb.StringReader()).vTableGetNullable(_bc, _bcOffset, 10);
  List<int>? get numberValues => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 12);
  List<int>? get end => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 14);
  List<int>? get start => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 16);

  @override
  String toString() {
    return 'ModelIndex{name: ${name}, stringKeys: ${stringKeys}, numberKeys: ${numberKeys}, stringValues: ${stringValues}, numberValues: ${numberValues}, end: ${end}, start: ${start}}';
  }
}

class _ModelIndexReader extends fb.TableReader<ModelIndex> {
  const _ModelIndexReader();

  @override
  ModelIndex createObject(fb.BufferContext bc, int offset) => 
    ModelIndex._(bc, offset);
}

class ModelIndexBuilder {
  ModelIndexBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(7);
  }

  int addNameOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addStringKeysOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addNumberKeysOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addStringValuesOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }
  int addNumberValuesOffset(int? offset) {
    fbBuilder.addOffset(4, offset);
    return fbBuilder.offset;
  }
  int addEndOffset(int? offset) {
    fbBuilder.addOffset(5, offset);
    return fbBuilder.offset;
  }
  int addStartOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ModelIndexObjectBuilder extends fb.ObjectBuilder {
  final String? _name;
  final List<String>? _stringKeys;
  final List<int>? _numberKeys;
  final List<String>? _stringValues;
  final List<int>? _numberValues;
  final List<int>? _end;
  final List<int>? _start;

  ModelIndexObjectBuilder({
    String? name,
    List<String>? stringKeys,
    List<int>? numberKeys,
    List<String>? stringValues,
    List<int>? numberValues,
    List<int>? end,
    List<int>? start,
  })
      : _name = name,
        _stringKeys = stringKeys,
        _numberKeys = numberKeys,
        _stringValues = stringValues,
        _numberValues = numberValues,
        _end = end,
        _start = start;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = _name == null ? null
        : fbBuilder.writeString(_name!);
    final int? stringKeysOffset = _stringKeys == null ? null
        : fbBuilder.writeList(_stringKeys!.map(fbBuilder.writeString).toList());
    final int? numberKeysOffset = _numberKeys == null ? null
        : fbBuilder.writeListUint32(_numberKeys!);
    final int? stringValuesOffset = _stringValues == null ? null
        : fbBuilder.writeList(_stringValues!.map(fbBuilder.writeString).toList());
    final int? numberValuesOffset = _numberValues == null ? null
        : fbBuilder.writeListUint32(_numberValues!);
    final int? endOffset = _end == null ? null
        : fbBuilder.writeListUint32(_end!);
    final int? startOffset = _start == null ? null
        : fbBuilder.writeListUint32(_start!);
    fbBuilder.startTable(7);
    fbBuilder.addOffset(0, nameOffset);
    fbBuilder.addOffset(1, stringKeysOffset);
    fbBuilder.addOffset(2, numberKeysOffset);
    fbBuilder.addOffset(3, stringValuesOffset);
    fbBuilder.addOffset(4, numberValuesOffset);
    fbBuilder.addOffset(5, endOffset);
    fbBuilder.addOffset(6, startOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Model {
  Model._(this._bc, this._bcOffset);
  factory Model(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Model> reader = _ModelReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get metadata => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  List<String>? get guids => const fb.ListReader<String>(fb.StringReader()).vTableGetNullable(_bc, _bcOffset, 6);
  List<int>? get guidsItems => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 8);
  int get maxLocalId => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 10, 0);
  List<int>? get localIds => const fb.ListReader<int>(fb.Uint32Reader()).vTableGetNullable(_bc, _bcOffset, 12);
  List<String>? get categories => const fb.ListReader<String>(fb.StringReader()).vTableGetNullable(_bc, _bcOffset, 14);
  Meshes? get meshes => Meshes.reader.vTableGetNullable(_bc, _bcOffset, 16);
  List<Attribute>? get attributes => const fb.ListReader<Attribute>(Attribute.reader).vTableGetNullable(_bc, _bcOffset, 18);
  List<Relation>? get relations => const fb.ListReader<Relation>(Relation.reader).vTableGetNullable(_bc, _bcOffset, 20);
  List<int>? get relationsItems => const fb.ListReader<int>(fb.Int32Reader()).vTableGetNullable(_bc, _bcOffset, 22);
  String? get guid => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 24);
  SpatialStructure? get spatialStructure => SpatialStructure.reader.vTableGetNullable(_bc, _bcOffset, 26);
  List<String>? get uniqueAttributes => const fb.ListReader<String>(fb.StringReader()).vTableGetNullable(_bc, _bcOffset, 28);
  List<String>? get relationNames => const fb.ListReader<String>(fb.StringReader()).vTableGetNullable(_bc, _bcOffset, 30);
  List<ModelIndex>? get indexes => const fb.ListReader<ModelIndex>(ModelIndex.reader).vTableGetNullable(_bc, _bcOffset, 32);

  @override
  String toString() {
    return 'Model{metadata: ${metadata}, guids: ${guids}, guidsItems: ${guidsItems}, maxLocalId: ${maxLocalId}, localIds: ${localIds}, categories: ${categories}, meshes: ${meshes}, attributes: ${attributes}, relations: ${relations}, relationsItems: ${relationsItems}, guid: ${guid}, spatialStructure: ${spatialStructure}, uniqueAttributes: ${uniqueAttributes}, relationNames: ${relationNames}, indexes: ${indexes}}';
  }
}

class _ModelReader extends fb.TableReader<Model> {
  const _ModelReader();

  @override
  Model createObject(fb.BufferContext bc, int offset) => 
    Model._(bc, offset);
}

class ModelBuilder {
  ModelBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(15);
  }

  int addMetadataOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addGuidsOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addGuidsItemsOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addMaxLocalId(int? maxLocalId) {
    fbBuilder.addUint32(3, maxLocalId);
    return fbBuilder.offset;
  }
  int addLocalIdsOffset(int? offset) {
    fbBuilder.addOffset(4, offset);
    return fbBuilder.offset;
  }
  int addCategoriesOffset(int? offset) {
    fbBuilder.addOffset(5, offset);
    return fbBuilder.offset;
  }
  int addMeshesOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }
  int addAttributesOffset(int? offset) {
    fbBuilder.addOffset(7, offset);
    return fbBuilder.offset;
  }
  int addRelationsOffset(int? offset) {
    fbBuilder.addOffset(8, offset);
    return fbBuilder.offset;
  }
  int addRelationsItemsOffset(int? offset) {
    fbBuilder.addOffset(9, offset);
    return fbBuilder.offset;
  }
  int addGuidOffset(int? offset) {
    fbBuilder.addOffset(10, offset);
    return fbBuilder.offset;
  }
  int addSpatialStructureOffset(int? offset) {
    fbBuilder.addOffset(11, offset);
    return fbBuilder.offset;
  }
  int addUniqueAttributesOffset(int? offset) {
    fbBuilder.addOffset(12, offset);
    return fbBuilder.offset;
  }
  int addRelationNamesOffset(int? offset) {
    fbBuilder.addOffset(13, offset);
    return fbBuilder.offset;
  }
  int addIndexesOffset(int? offset) {
    fbBuilder.addOffset(14, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ModelObjectBuilder extends fb.ObjectBuilder {
  final String? _metadata;
  final List<String>? _guids;
  final List<int>? _guidsItems;
  final int? _maxLocalId;
  final List<int>? _localIds;
  final List<String>? _categories;
  final MeshesObjectBuilder? _meshes;
  final List<AttributeObjectBuilder>? _attributes;
  final List<RelationObjectBuilder>? _relations;
  final List<int>? _relationsItems;
  final String? _guid;
  final SpatialStructureObjectBuilder? _spatialStructure;
  final List<String>? _uniqueAttributes;
  final List<String>? _relationNames;
  final List<ModelIndexObjectBuilder>? _indexes;

  ModelObjectBuilder({
    String? metadata,
    List<String>? guids,
    List<int>? guidsItems,
    int? maxLocalId,
    List<int>? localIds,
    List<String>? categories,
    MeshesObjectBuilder? meshes,
    List<AttributeObjectBuilder>? attributes,
    List<RelationObjectBuilder>? relations,
    List<int>? relationsItems,
    String? guid,
    SpatialStructureObjectBuilder? spatialStructure,
    List<String>? uniqueAttributes,
    List<String>? relationNames,
    List<ModelIndexObjectBuilder>? indexes,
  })
      : _metadata = metadata,
        _guids = guids,
        _guidsItems = guidsItems,
        _maxLocalId = maxLocalId,
        _localIds = localIds,
        _categories = categories,
        _meshes = meshes,
        _attributes = attributes,
        _relations = relations,
        _relationsItems = relationsItems,
        _guid = guid,
        _spatialStructure = spatialStructure,
        _uniqueAttributes = uniqueAttributes,
        _relationNames = relationNames,
        _indexes = indexes;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? metadataOffset = _metadata == null ? null
        : fbBuilder.writeString(_metadata!);
    final int? guidsOffset = _guids == null ? null
        : fbBuilder.writeList(_guids!.map(fbBuilder.writeString).toList());
    final int? guidsItemsOffset = _guidsItems == null ? null
        : fbBuilder.writeListUint32(_guidsItems!);
    final int? localIdsOffset = _localIds == null ? null
        : fbBuilder.writeListUint32(_localIds!);
    final int? categoriesOffset = _categories == null ? null
        : fbBuilder.writeList(_categories!.map(fbBuilder.writeString).toList());
    final int? meshesOffset = _meshes?.getOrCreateOffset(fbBuilder);
    final int? attributesOffset = _attributes == null ? null
        : fbBuilder.writeList(_attributes!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? relationsOffset = _relations == null ? null
        : fbBuilder.writeList(_relations!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? relationsItemsOffset = _relationsItems == null ? null
        : fbBuilder.writeListInt32(_relationsItems!);
    final int? guidOffset = _guid == null ? null
        : fbBuilder.writeString(_guid!);
    final int? spatialStructureOffset = _spatialStructure?.getOrCreateOffset(fbBuilder);
    final int? uniqueAttributesOffset = _uniqueAttributes == null ? null
        : fbBuilder.writeList(_uniqueAttributes!.map(fbBuilder.writeString).toList());
    final int? relationNamesOffset = _relationNames == null ? null
        : fbBuilder.writeList(_relationNames!.map(fbBuilder.writeString).toList());
    final int? indexesOffset = _indexes == null ? null
        : fbBuilder.writeList(_indexes!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(15);
    fbBuilder.addOffset(0, metadataOffset);
    fbBuilder.addOffset(1, guidsOffset);
    fbBuilder.addOffset(2, guidsItemsOffset);
    fbBuilder.addUint32(3, _maxLocalId);
    fbBuilder.addOffset(4, localIdsOffset);
    fbBuilder.addOffset(5, categoriesOffset);
    fbBuilder.addOffset(6, meshesOffset);
    fbBuilder.addOffset(7, attributesOffset);
    fbBuilder.addOffset(8, relationsOffset);
    fbBuilder.addOffset(9, relationsItemsOffset);
    fbBuilder.addOffset(10, guidOffset);
    fbBuilder.addOffset(11, spatialStructureOffset);
    fbBuilder.addOffset(12, uniqueAttributesOffset);
    fbBuilder.addOffset(13, relationNamesOffset);
    fbBuilder.addOffset(14, indexesOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
