"""Generated FlatBuffers Python bindings for ThatOpen's public Fragments
(``.frag``) binary schema - see ``index.fbs`` in this directory for the
vendored schema source and regeneration instructions.

Every module in this package (other than ``index.fbs`` itself) is
machine-generated by ``flatc`` - do not hand-edit; regenerate instead.
Not part of OpenSKP's public API; used internally by
:mod:`openskp.export.fragments`.
"""
