# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fragments_fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Axis(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Axis()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAxis(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def AxisBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x30\x30\x30\x31", size_prefixed=size_prefixed)

    # Axis
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Axis
    def Wires(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 24
            from openskp._fragments_fb.Wire import Wire
            obj = Wire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Axis
    def WiresLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Axis
    def WiresIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Axis
    def Order(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Axis
    def OrderAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Axis
    def OrderLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Axis
    def OrderIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Axis
    def Parts(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Axis
    def PartsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # Axis
    def PartsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Axis
    def PartsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Axis
    def WireSets(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from openskp._fragments_fb.WireSet import WireSet
            obj = WireSet()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Axis
    def WireSetsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Axis
    def WireSetsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Axis
    def CircleCurves(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 44
            from openskp._fragments_fb.CircleCurve import CircleCurve
            obj = CircleCurve()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Axis
    def CircleCurvesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Axis
    def CircleCurvesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def AxisStart(builder):
    builder.StartObject(5)

def Start(builder):
    AxisStart(builder)

def AxisAddWires(builder, wires):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(wires), 0)

def AddWires(builder, wires):
    AxisAddWires(builder, wires)

def AxisStartWiresVector(builder, numElems):
    return builder.StartVector(24, numElems, 4)

def StartWiresVector(builder, numElems):
    return AxisStartWiresVector(builder, numElems)

def AxisAddOrder(builder, order):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(order), 0)

def AddOrder(builder, order):
    AxisAddOrder(builder, order)

def AxisStartOrderVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOrderVector(builder, numElems):
    return AxisStartOrderVector(builder, numElems)

def AxisAddParts(builder, parts):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(parts), 0)

def AddParts(builder, parts):
    AxisAddParts(builder, parts)

def AxisStartPartsVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartPartsVector(builder, numElems):
    return AxisStartPartsVector(builder, numElems)

def AxisAddWireSets(builder, wireSets):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(wireSets), 0)

def AddWireSets(builder, wireSets):
    AxisAddWireSets(builder, wireSets)

def AxisStartWireSetsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartWireSetsVector(builder, numElems):
    return AxisStartWireSetsVector(builder, numElems)

def AxisAddCircleCurves(builder, circleCurves):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(circleCurves), 0)

def AddCircleCurves(builder, circleCurves):
    AxisAddCircleCurves(builder, circleCurves)

def AxisStartCircleCurvesVector(builder, numElems):
    return builder.StartVector(44, numElems, 4)

def StartCircleCurvesVector(builder, numElems):
    return AxisStartCircleCurvesVector(builder, numElems)

def AxisEnd(builder):
    return builder.EndObject()

def End(builder):
    return AxisEnd(builder)
