# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fragments_fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CircleCurve(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 44

    # CircleCurve
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CircleCurve
    def Aperture(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # CircleCurve
    def Position(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 4)
        return obj

    # CircleCurve
    def Radius(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # CircleCurve
    def XDirection(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 20)
        return obj

    # CircleCurve
    def YDirection(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 32)
        return obj


def CreateCircleCurve(builder, aperture, position_x, position_y, position_z, radius, xDirection_x, xDirection_y, xDirection_z, yDirection_x, yDirection_y, yDirection_z):
    builder.Prep(4, 44)
    builder.Prep(4, 12)
    builder.PrependFloat32(yDirection_z)
    builder.PrependFloat32(yDirection_y)
    builder.PrependFloat32(yDirection_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(xDirection_z)
    builder.PrependFloat32(xDirection_y)
    builder.PrependFloat32(xDirection_x)
    builder.PrependFloat32(radius)
    builder.Prep(4, 12)
    builder.PrependFloat32(position_z)
    builder.PrependFloat32(position_y)
    builder.PrependFloat32(position_x)
    builder.PrependFloat32(aperture)
    return builder.Offset()
