# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fragments_fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CircleExtrusion(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CircleExtrusion()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCircleExtrusion(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CircleExtrusionBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x30\x30\x30\x31", size_prefixed=size_prefixed)

    # CircleExtrusion
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CircleExtrusion
    def Radius(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # CircleExtrusion
    def RadiusAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # CircleExtrusion
    def RadiusLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CircleExtrusion
    def RadiusIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # CircleExtrusion
    def Axes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from openskp._fragments_fb.Axis import Axis
            obj = Axis()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CircleExtrusion
    def AxesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CircleExtrusion
    def AxesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def CircleExtrusionStart(builder):
    builder.StartObject(2)

def Start(builder):
    CircleExtrusionStart(builder)

def CircleExtrusionAddRadius(builder, radius):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(radius), 0)

def AddRadius(builder, radius):
    CircleExtrusionAddRadius(builder, radius)

def CircleExtrusionStartRadiusVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartRadiusVector(builder, numElems):
    return CircleExtrusionStartRadiusVector(builder, numElems)

def CircleExtrusionAddAxes(builder, axes):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(axes), 0)

def AddAxes(builder, axes):
    CircleExtrusionAddAxes(builder, axes)

def CircleExtrusionStartAxesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAxesVector(builder, numElems):
    return CircleExtrusionStartAxesVector(builder, numElems)

def CircleExtrusionEnd(builder):
    return builder.EndObject()

def End(builder):
    return CircleExtrusionEnd(builder)
