# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fragments_fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Meshes(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Meshes()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMeshes(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MeshesBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x30\x30\x30\x31", size_prefixed=size_prefixed)

    # Meshes
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Meshes
    def Coordinates(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from openskp._fragments_fb.Transform import Transform
            obj = Transform()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Meshes
    def MeshesItems(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Meshes
    def MeshesItemsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Meshes
    def MeshesItemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def MeshesItemsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Meshes
    def Samples(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 16
            from openskp._fragments_fb.Sample import Sample
            obj = Sample()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Meshes
    def SamplesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def SamplesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Meshes
    def Representations(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 32
            from openskp._fragments_fb.Representation import Representation
            obj = Representation()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Meshes
    def RepresentationsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def RepresentationsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Meshes
    def Materials(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 6
            from openskp._fragments_fb.Material import Material
            obj = Material()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Meshes
    def MaterialsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def MaterialsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Meshes
    def CircleExtrusions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from openskp._fragments_fb.CircleExtrusion import CircleExtrusion
            obj = CircleExtrusion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Meshes
    def CircleExtrusionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def CircleExtrusionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # Meshes
    def Shells(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from openskp._fragments_fb.Shell import Shell
            obj = Shell()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Meshes
    def ShellsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def ShellsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # Meshes
    def LocalTransforms(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 48
            from openskp._fragments_fb.Transform import Transform
            obj = Transform()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Meshes
    def LocalTransformsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def LocalTransformsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # Meshes
    def GlobalTransforms(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 48
            from openskp._fragments_fb.Transform import Transform
            obj = Transform()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Meshes
    def GlobalTransformsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def GlobalTransformsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # Meshes
    def MaterialIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Meshes
    def MaterialIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Meshes
    def MaterialIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def MaterialIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

    # Meshes
    def RepresentationIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Meshes
    def RepresentationIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Meshes
    def RepresentationIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def RepresentationIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

    # Meshes
    def SampleIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Meshes
    def SampleIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Meshes
    def SampleIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def SampleIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        return o == 0

    # Meshes
    def LocalTransformIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Meshes
    def LocalTransformIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Meshes
    def LocalTransformIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def LocalTransformIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        return o == 0

    # Meshes
    def GlobalTransformIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Meshes
    def GlobalTransformIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Meshes
    def GlobalTransformIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Meshes
    def GlobalTransformIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        return o == 0

def MeshesStart(builder):
    builder.StartObject(14)

def Start(builder):
    MeshesStart(builder)

def MeshesAddCoordinates(builder, coordinates):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(coordinates), 0)

def AddCoordinates(builder, coordinates):
    MeshesAddCoordinates(builder, coordinates)

def MeshesAddMeshesItems(builder, meshesItems):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(meshesItems), 0)

def AddMeshesItems(builder, meshesItems):
    MeshesAddMeshesItems(builder, meshesItems)

def MeshesStartMeshesItemsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMeshesItemsVector(builder, numElems):
    return MeshesStartMeshesItemsVector(builder, numElems)

def MeshesAddSamples(builder, samples):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(samples), 0)

def AddSamples(builder, samples):
    MeshesAddSamples(builder, samples)

def MeshesStartSamplesVector(builder, numElems):
    return builder.StartVector(16, numElems, 4)

def StartSamplesVector(builder, numElems):
    return MeshesStartSamplesVector(builder, numElems)

def MeshesAddRepresentations(builder, representations):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(representations), 0)

def AddRepresentations(builder, representations):
    MeshesAddRepresentations(builder, representations)

def MeshesStartRepresentationsVector(builder, numElems):
    return builder.StartVector(32, numElems, 4)

def StartRepresentationsVector(builder, numElems):
    return MeshesStartRepresentationsVector(builder, numElems)

def MeshesAddMaterials(builder, materials):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(materials), 0)

def AddMaterials(builder, materials):
    MeshesAddMaterials(builder, materials)

def MeshesStartMaterialsVector(builder, numElems):
    return builder.StartVector(6, numElems, 1)

def StartMaterialsVector(builder, numElems):
    return MeshesStartMaterialsVector(builder, numElems)

def MeshesAddCircleExtrusions(builder, circleExtrusions):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(circleExtrusions), 0)

def AddCircleExtrusions(builder, circleExtrusions):
    MeshesAddCircleExtrusions(builder, circleExtrusions)

def MeshesStartCircleExtrusionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCircleExtrusionsVector(builder, numElems):
    return MeshesStartCircleExtrusionsVector(builder, numElems)

def MeshesAddShells(builder, shells):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(shells), 0)

def AddShells(builder, shells):
    MeshesAddShells(builder, shells)

def MeshesStartShellsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartShellsVector(builder, numElems):
    return MeshesStartShellsVector(builder, numElems)

def MeshesAddLocalTransforms(builder, localTransforms):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(localTransforms), 0)

def AddLocalTransforms(builder, localTransforms):
    MeshesAddLocalTransforms(builder, localTransforms)

def MeshesStartLocalTransformsVector(builder, numElems):
    return builder.StartVector(48, numElems, 8)

def StartLocalTransformsVector(builder, numElems):
    return MeshesStartLocalTransformsVector(builder, numElems)

def MeshesAddGlobalTransforms(builder, globalTransforms):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(globalTransforms), 0)

def AddGlobalTransforms(builder, globalTransforms):
    MeshesAddGlobalTransforms(builder, globalTransforms)

def MeshesStartGlobalTransformsVector(builder, numElems):
    return builder.StartVector(48, numElems, 8)

def StartGlobalTransformsVector(builder, numElems):
    return MeshesStartGlobalTransformsVector(builder, numElems)

def MeshesAddMaterialIds(builder, materialIds):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(materialIds), 0)

def AddMaterialIds(builder, materialIds):
    MeshesAddMaterialIds(builder, materialIds)

def MeshesStartMaterialIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMaterialIdsVector(builder, numElems):
    return MeshesStartMaterialIdsVector(builder, numElems)

def MeshesAddRepresentationIds(builder, representationIds):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(representationIds), 0)

def AddRepresentationIds(builder, representationIds):
    MeshesAddRepresentationIds(builder, representationIds)

def MeshesStartRepresentationIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRepresentationIdsVector(builder, numElems):
    return MeshesStartRepresentationIdsVector(builder, numElems)

def MeshesAddSampleIds(builder, sampleIds):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(sampleIds), 0)

def AddSampleIds(builder, sampleIds):
    MeshesAddSampleIds(builder, sampleIds)

def MeshesStartSampleIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSampleIdsVector(builder, numElems):
    return MeshesStartSampleIdsVector(builder, numElems)

def MeshesAddLocalTransformIds(builder, localTransformIds):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(localTransformIds), 0)

def AddLocalTransformIds(builder, localTransformIds):
    MeshesAddLocalTransformIds(builder, localTransformIds)

def MeshesStartLocalTransformIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartLocalTransformIdsVector(builder, numElems):
    return MeshesStartLocalTransformIdsVector(builder, numElems)

def MeshesAddGlobalTransformIds(builder, globalTransformIds):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(globalTransformIds), 0)

def AddGlobalTransformIds(builder, globalTransformIds):
    MeshesAddGlobalTransformIds(builder, globalTransformIds)

def MeshesStartGlobalTransformIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartGlobalTransformIdsVector(builder, numElems):
    return MeshesStartGlobalTransformIdsVector(builder, numElems)

def MeshesEnd(builder):
    return builder.EndObject()

def End(builder):
    return MeshesEnd(builder)
