# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fragments_fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Representation(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 32

    # Representation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Representation
    def Id(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Representation
    def Bbox(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 4)
        return obj

    # Representation
    def RepresentationClass(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(28))

def CreateRepresentation(builder, id, bbox_min_x, bbox_min_y, bbox_min_z, bbox_max_x, bbox_max_y, bbox_max_z, representationClass):
    builder.Prep(4, 32)
    builder.Pad(3)
    builder.PrependInt8(representationClass)
    builder.Prep(4, 24)
    builder.Prep(4, 12)
    builder.PrependFloat32(bbox_max_z)
    builder.PrependFloat32(bbox_max_y)
    builder.PrependFloat32(bbox_max_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(bbox_min_z)
    builder.PrependFloat32(bbox_min_y)
    builder.PrependFloat32(bbox_min_x)
    builder.PrependUint32(id)
    return builder.Offset()
