# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fragments_fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ShellHole(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ShellHole()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShellHole(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ShellHoleBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x30\x30\x30\x31", size_prefixed=size_prefixed)

    # ShellHole
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ShellHole
    def Indices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # ShellHole
    def IndicesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # ShellHole
    def IndicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ShellHole
    def IndicesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # ShellHole
    def ProfileId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def ShellHoleStart(builder):
    builder.StartObject(2)

def Start(builder):
    ShellHoleStart(builder)

def ShellHoleAddIndices(builder, indices):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(indices), 0)

def AddIndices(builder, indices):
    ShellHoleAddIndices(builder, indices)

def ShellHoleStartIndicesVector(builder, numElems):
    return builder.StartVector(2, numElems, 2)

def StartIndicesVector(builder, numElems):
    return ShellHoleStartIndicesVector(builder, numElems)

def ShellHoleAddProfileId(builder, profileId):
    builder.PrependUint16Slot(1, profileId, 0)

def AddProfileId(builder, profileId):
    ShellHoleAddProfileId(builder, profileId)

def ShellHoleEnd(builder):
    return builder.EndObject()

def End(builder):
    return ShellHoleEnd(builder)
