# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fragments_fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Shell(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Shell()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShell(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ShellBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x30\x30\x30\x31", size_prefixed=size_prefixed)

    # Shell
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Shell
    def Profiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from openskp._fragments_fb.ShellProfile import ShellProfile
            obj = ShellProfile()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Shell
    def ProfilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Shell
    def ProfilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Shell
    def Holes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from openskp._fragments_fb.ShellHole import ShellHole
            obj = ShellHole()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Shell
    def HolesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Shell
    def HolesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Shell
    def Points(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            from openskp._fragments_fb.FloatVector import FloatVector
            obj = FloatVector()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Shell
    def PointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Shell
    def PointsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Shell
    def BigProfiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from openskp._fragments_fb.BigShellProfile import BigShellProfile
            obj = BigShellProfile()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Shell
    def BigProfilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Shell
    def BigProfilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Shell
    def BigHoles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from openskp._fragments_fb.BigShellHole import BigShellHole
            obj = BigShellHole()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Shell
    def BigHolesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Shell
    def BigHolesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Shell
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Shell
    def ProfilesFaceIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # Shell
    def ProfilesFaceIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # Shell
    def ProfilesFaceIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Shell
    def ProfilesFaceIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def ShellStart(builder):
    builder.StartObject(7)

def Start(builder):
    ShellStart(builder)

def ShellAddProfiles(builder, profiles):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(profiles), 0)

def AddProfiles(builder, profiles):
    ShellAddProfiles(builder, profiles)

def ShellStartProfilesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartProfilesVector(builder, numElems):
    return ShellStartProfilesVector(builder, numElems)

def ShellAddHoles(builder, holes):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(holes), 0)

def AddHoles(builder, holes):
    ShellAddHoles(builder, holes)

def ShellStartHolesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartHolesVector(builder, numElems):
    return ShellStartHolesVector(builder, numElems)

def ShellAddPoints(builder, points):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(points), 0)

def AddPoints(builder, points):
    ShellAddPoints(builder, points)

def ShellStartPointsVector(builder, numElems):
    return builder.StartVector(12, numElems, 4)

def StartPointsVector(builder, numElems):
    return ShellStartPointsVector(builder, numElems)

def ShellAddBigProfiles(builder, bigProfiles):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(bigProfiles), 0)

def AddBigProfiles(builder, bigProfiles):
    ShellAddBigProfiles(builder, bigProfiles)

def ShellStartBigProfilesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartBigProfilesVector(builder, numElems):
    return ShellStartBigProfilesVector(builder, numElems)

def ShellAddBigHoles(builder, bigHoles):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(bigHoles), 0)

def AddBigHoles(builder, bigHoles):
    ShellAddBigHoles(builder, bigHoles)

def ShellStartBigHolesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartBigHolesVector(builder, numElems):
    return ShellStartBigHolesVector(builder, numElems)

def ShellAddType(builder, type):
    builder.PrependInt8Slot(5, type, 0)

def AddType(builder, type):
    ShellAddType(builder, type)

def ShellAddProfilesFaceIds(builder, profilesFaceIds):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(profilesFaceIds), 0)

def AddProfilesFaceIds(builder, profilesFaceIds):
    ShellAddProfilesFaceIds(builder, profilesFaceIds)

def ShellStartProfilesFaceIdsVector(builder, numElems):
    return builder.StartVector(2, numElems, 2)

def StartProfilesFaceIdsVector(builder, numElems):
    return ShellStartProfilesFaceIdsVector(builder, numElems)

def ShellEnd(builder):
    return builder.EndObject()

def End(builder):
    return ShellEnd(builder)
