# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fragments_fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SpatialStructure(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SpatialStructure()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSpatialStructure(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SpatialStructureBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x30\x30\x30\x31", size_prefixed=size_prefixed)

    # SpatialStructure
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SpatialStructure
    def LocalId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return None

    # SpatialStructure
    def Category(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SpatialStructure
    def Children(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from openskp._fragments_fb.SpatialStructure import SpatialStructure
            obj = SpatialStructure()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SpatialStructure
    def ChildrenLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SpatialStructure
    def ChildrenIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def SpatialStructureStart(builder):
    builder.StartObject(3)

def Start(builder):
    SpatialStructureStart(builder)

def SpatialStructureAddLocalId(builder, localId):
    builder.PrependUint32Slot(0, localId, None)

def AddLocalId(builder, localId):
    SpatialStructureAddLocalId(builder, localId)

def SpatialStructureAddCategory(builder, category):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(category), 0)

def AddCategory(builder, category):
    SpatialStructureAddCategory(builder, category)

def SpatialStructureAddChildren(builder, children):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(children), 0)

def AddChildren(builder, children):
    SpatialStructureAddChildren(builder, children)

def SpatialStructureStartChildrenVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartChildrenVector(builder, numElems):
    return SpatialStructureStartChildrenVector(builder, numElems)

def SpatialStructureEnd(builder):
    return builder.EndObject()

def End(builder):
    return SpatialStructureEnd(builder)
