# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fragments_fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Transform(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 48

    # Transform
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Transform
    def Position(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # Transform
    def XDirection(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 24)
        return obj

    # Transform
    def YDirection(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 36)
        return obj


def CreateTransform(builder, position_x, position_y, position_z, xDirection_x, xDirection_y, xDirection_z, yDirection_x, yDirection_y, yDirection_z):
    builder.Prep(8, 48)
    builder.Prep(4, 12)
    builder.PrependFloat32(yDirection_z)
    builder.PrependFloat32(yDirection_y)
    builder.PrependFloat32(yDirection_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(xDirection_z)
    builder.PrependFloat32(xDirection_y)
    builder.PrependFloat32(xDirection_x)
    builder.Prep(8, 24)
    builder.PrependFloat64(position_z)
    builder.PrependFloat64(position_y)
    builder.PrependFloat64(position_x)
    return builder.Offset()
