# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fragments_fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WireSet(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WireSet()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWireSet(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def WireSetBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x30\x30\x30\x31", size_prefixed=size_prefixed)

    # WireSet
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WireSet
    def Ps(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            from openskp._fragments_fb.FloatVector import FloatVector
            obj = FloatVector()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WireSet
    def PsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WireSet
    def PsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def WireSetStart(builder):
    builder.StartObject(1)

def Start(builder):
    WireSetStart(builder)

def WireSetAddPs(builder, ps):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(ps), 0)

def AddPs(builder, ps):
    WireSetAddPs(builder, ps)

def WireSetStartPsVector(builder, numElems):
    return builder.StartVector(12, numElems, 4)

def StartPsVector(builder, numElems):
    return WireSetStartPsVector(builder, numElems)

def WireSetEnd(builder):
    return builder.EndObject()

def End(builder):
    return WireSetEnd(builder)
