# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fragments_fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Wire(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 24

    # Wire
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Wire
    def P1(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # Wire
    def P2(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 12)
        return obj


def CreateWire(builder, p1_x, p1_y, p1_z, p2_x, p2_y, p2_z):
    builder.Prep(4, 24)
    builder.Prep(4, 12)
    builder.PrependFloat32(p2_z)
    builder.PrependFloat32(p2_y)
    builder.PrependFloat32(p2_x)
    builder.Prep(4, 12)
    builder.PrependFloat32(p1_z)
    builder.PrependFloat32(p1_y)
    builder.PrependFloat32(p1_x)
    return builder.Offset()
