// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace openskp._fragments_fb
{

public enum RenderedFaces : sbyte
{
  ONE = 0,
  TWO = 1,
};


}
