// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace openskp._fragments_fb
{

public enum RepresentationClass : sbyte
{
  NONE = 0,
  SHELL = 1,
  CIRCLE_EXTRUSION = 2,
};


}
