// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace openskp._fragments_fb
{

public enum ShellType : sbyte
{
  NONE = 0,
  BIG = 1,
};


}
