import 'dart:io';
import 'dart:math';

import 'package:openskp/openskp.dart';
import 'package:test/test.dart';

/// Tests for the `create.dart` from-scratch legacy (v17) `.skp` writer -
/// the Dart port of Python's `openskp.create` (see `test_create.py` for the
/// reference suite this mirrors).
///
/// Two complementary validation strategies are used throughout, matching
/// this project's established practice:
///
/// 1. Self-parsing a written file with this package's own reader
///    ([SkpFile.parse]) proves internal round-trip consistency - the
///    primary technique used below.
/// 2. For scenes with no random UUIDs/timestamps involved (i.e. no
///    component definitions/instances/groups), byte-for-byte comparison
///    against reference files pre-generated by the real, SDK-validated
///    Python writer (`test/fixtures/create_reference/*.skp`, produced by a
///    one-off script - see that directory) proves true cross-language
///    parity, not just self-consistency.
void main() {
  final referenceDir = '${Directory.current.path}/test/fixtures/create_reference';

  const square = [
    (0.0, 0.0, 0.0), (100.0, 0.0, 0.0), (100.0, 100.0, 0.0), (0.0, 100.0, 0.0),
  ];

  group('cross-validation against Python-written reference bytes', () {
    test('single face matches Python byte-for-byte', () {
      final builder = create();
      builder.addFace(square);
      final expected = File('$referenceDir/single_face.skp').readAsBytesSync();
      expect(builder.toBytes(), equals(expected));
    });

    test('two faces sharing an edge match Python byte-for-byte', () {
      final builder = create();
      const face1 = [
        (0.0, 0.0, 0.0), (100.0, 0.0, 0.0), (100.0, 100.0, 0.0), (0.0, 100.0, 0.0),
      ];
      const face2 = [
        (100.0, 0.0, 0.0), (200.0, 0.0, 0.0), (200.0, 100.0, 0.0), (100.0, 100.0, 0.0),
      ];
      builder.addFace(face1);
      builder.addFace(face2);
      final expected = File('$referenceDir/multi_face_shared_edge.skp').readAsBytesSync();
      expect(builder.toBytes(), equals(expected));
    });

    test('materials and layers match Python byte-for-byte', () {
      final builder = create();
      final red = builder.addMaterial('Red', [255, 0, 0]);
      final blue = builder.addMaterial('Blue', [0, 0, 255, 128]);
      final roof = builder.addLayer('Roof', color: [10, 20, 30]);
      final walls = builder.addLayer('Walls', hidden: true);
      builder.addFace(square, material: red, layer: roof);
      builder.addFace(
        [(0.0, 0.0, 10.0), (100.0, 0.0, 10.0), (100.0, 100.0, 10.0), (0.0, 100.0, 10.0)],
        material: blue,
        backMaterial: red,
        layer: walls,
      );
      final expected = File('$referenceDir/materials_and_layers.skp').readAsBytesSync();
      expect(builder.toBytes(), equals(expected));
    });

    test('a face with a hole matches Python byte-for-byte', () {
      final builder = create();
      const wall = [
        (0.0, 0.0, 0.0), (200.0, 0.0, 0.0), (200.0, 100.0, 0.0), (0.0, 100.0, 0.0),
      ];
      const window = [
        (80.0, 30.0, 0.0), (120.0, 30.0, 0.0), (120.0, 70.0, 0.0), (80.0, 70.0, 0.0),
      ];
      builder.addFace(wall, holes: [window]);
      final expected = File('$referenceDir/holes.skp').readAsBytesSync();
      expect(builder.toBytes(), equals(expected));
    });

    test('auto-triangulated face matches Python byte-for-byte', () {
      final builder = create();
      const warped = [
        (0.0, 0.0, 0.0), (10.0, 0.0, 0.0), (10.0, 10.0, 0.0), (0.0, 10.0, 5.0),
      ];
      builder.addFace(warped, autoTriangulate: true);
      final expected = File('$referenceDir/auto_triangulate.skp').readAsBytesSync();
      expect(builder.toBytes(), equals(expected));
    });

    // Circle/arc points come from cos()/sin(), which IEEE 754 does not
    // guarantee bit-identical results for across platforms/architectures -
    // a 1-ULP difference on some CI runners' math library flips a single
    // byte deep in an f64 vertex coordinate despite the geometry being
    // correct (confirmed: the TypeScript port hit the same class of
    // difference and documented it as expected, not a bug). So these two
    // compare the actual decoded geometry within float tolerance, the same
    // way every other non-deterministic-bytes test in this file does,
    // rather than raw byte equality - still a real cross-language
    // correctness check, just not sensitive to platform trig rounding.
    test('a circle matches Python numerically', () {
      final builder = create();
      builder.addCircle((50.0, 50.0, 0.0), (0.0, 0.0, 1.0), 40.0, numSegments: 12);
      final ours = SkpFile.fromBuffer(builder.toBytes()).parse();
      final expectedBytes = File('$referenceDir/circle.skp').readAsBytesSync();
      final theirs = SkpFile.fromBuffer(expectedBytes).parse();
      expect(ours.root.faces.length, theirs.root.faces.length);
      expect(ours.root.edges.length, theirs.root.edges.length);
      expect(ours.root.vertices.length, theirs.root.vertices.length);
      final oursV = ours.root.vertices.values.toList();
      final theirsV = theirs.root.vertices.values.toList();
      for (var i = 0; i < oursV.length; i++) {
        expect(oursV[i].x, closeTo(theirsV[i].x, 1e-9));
        expect(oursV[i].y, closeTo(theirsV[i].y, 1e-9));
        expect(oursV[i].z, closeTo(theirsV[i].z, 1e-9));
      }
    });

    test('an arc matches Python numerically', () {
      final builder = create();
      builder.addArc(
        (50.0, 50.0, 0.0), (0.0, 0.0, 1.0), 40.0, 0.0, pi / 2,
        numSegments: 8,
      );
      final ours = SkpFile.fromBuffer(builder.toBytes()).parse();
      final expectedBytes = File('$referenceDir/arc.skp').readAsBytesSync();
      final theirs = SkpFile.fromBuffer(expectedBytes).parse();
      expect(ours.root.edges.length, theirs.root.edges.length);
      expect(ours.root.vertices.length, theirs.root.vertices.length);
      final oursV = ours.root.vertices.values.toList();
      final theirsV = theirs.root.vertices.values.toList();
      for (var i = 0; i < oursV.length; i++) {
        expect(oursV[i].x, closeTo(theirsV[i].x, 1e-9));
        expect(oursV[i].y, closeTo(theirsV[i].y, 1e-9));
        expect(oursV[i].z, closeTo(theirsV[i].z, 1e-9));
      }
    });

    test('a closed polyline matches Python byte-for-byte', () {
      final builder = create();
      builder.addPolyline(
        [(0.0, 0.0, 0.0), (10.0, 10.0, 0.0), (20.0, 0.0, 0.0), (30.0, 10.0, 0.0)],
        closed: true,
      );
      final expected = File('$referenceDir/polyline.skp').readAsBytesSync();
      expect(builder.toBytes(), equals(expected));
    });

    test('face attributes match Python byte-for-byte', () {
      final builder = create();
      builder.addFace(
        square,
        attributes: {'part_number': 'A-100', 'count': 7, 'weight': 3.5},
      );
      final expected = File('$referenceDir/attributes.skp').readAsBytesSync();
      expect(builder.toBytes(), equals(expected));
    });

    // A textured material embeds its source file's own path string
    // verbatim (see write_textured_material's own ground-truth note) - not
    // reproducible byte-for-byte across machines/temp directories, so
    // texture round-tripping is covered functionally instead, in the
    // Textures group below.
  });

  group('SingleFace', () {
    test('self-parses to a single quad face', () {
      final builder = create();
      builder.addFace(square);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.root.faces.length, 1);
      expect(model.root.edges.length, 4);
      expect(model.root.vertices.length, 4);
      final face = model.root.faces.values.first;
      expect(face.normal, isNotNull);
      expect(face.normal!.$1, closeTo(0.0, 1e-9));
      expect(face.normal!.$2, closeTo(0.0, 1e-9));
      expect(face.normal!.$3, closeTo(1.0, 1e-9));
    });

    test('hidden/soft/smooth flags round-trip', () {
      final builder = create();
      builder.addFace(square, hidden: true, softEdges: true, smoothEdges: true, hiddenEdges: true);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      final face = model.root.faces.values.first;
      expect(face.hidden, isTrue);
      expect(model.root.edges.values.every((e) => e.hidden && e.soft && e.smooth), isTrue);
    });

    test('default flags are off', () {
      final builder = create();
      builder.addFace(square);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      final face = model.root.faces.values.first;
      expect(face.hidden, isFalse);
      expect(model.root.edges.values.every((e) => !e.hidden && !e.soft && !e.smooth), isTrue);
    });
  });

  group('MultiFace', () {
    test('shares vertices and edges across faces', () {
      const face1 = [
        (0.0, 0.0, 0.0), (100.0, 0.0, 0.0), (100.0, 100.0, 0.0), (0.0, 100.0, 0.0),
      ];
      const face2 = [
        (100.0, 0.0, 0.0), (200.0, 0.0, 0.0), (200.0, 100.0, 0.0), (100.0, 100.0, 0.0),
      ];
      final builder = create();
      builder.addFace(face1);
      builder.addFace(face2);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.root.faces.length, 2);
      expect(model.root.edges.length, 7); // 4 + 4 - 1 shared
      expect(model.root.vertices.length, 6); // 4 + 4 - 2 shared
    });

    test('a large disjoint mesh shifts tail references without byte overflow', () {
      // Regression coverage for the tail-reference renumbering: enough
      // slots consumed (30 disjoint quads) to need more than a single
      // byte's worth of shift.
      final builder = create();
      for (var i = 0; i < 30; i++) {
        final x0 = i * 200.0;
        builder.addFace([
          (x0, 0.0, 0.0), (x0 + 100.0, 0.0, 0.0),
          (x0 + 100.0, 100.0, 0.0), (x0, 100.0, 0.0),
        ]);
      }
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.root.faces.length, 30);
      expect(model.root.edges.length, 120);
    });
  });

  group('ConcavePolygons', () {
    test('a reflex-first-vertex L-shape still gets the correct normal', () {
      // 100x100 square missing its (50,50)-(100,100) corner, deliberately
      // starting at the reflex (concave) vertex - the worst case for a
      // plane-normal computation that only looks at the first 3 points.
      const lShape = [
        (50.0, 50.0, 0.0), (100.0, 50.0, 0.0), (100.0, 100.0, 0.0),
        (0.0, 100.0, 0.0), (0.0, 0.0, 0.0), (50.0, 0.0, 0.0),
      ];
      final builder = create();
      builder.addFace(lShape);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      final normal = model.root.faces.values.first.normal!;
      expect(normal.$1, closeTo(0.0, 1e-9));
      expect(normal.$2, closeTo(0.0, 1e-9));
      expect(normal.$3, closeTo(1.0, 1e-9));
    });
  });

  group('AutoTriangulate', () {
    const warpedQuad = [
      (0.0, 0.0, 0.0), (10.0, 0.0, 0.0), (10.0, 10.0, 0.0), (0.0, 10.0, 5.0),
    ];
    const flatSquare = [
      (0.0, 0.0, 0.0), (10.0, 0.0, 0.0), (10.0, 10.0, 0.0), (0.0, 10.0, 0.0),
    ];

    test('non-planar input without autoTriangulate still throws', () {
      final builder = create();
      expect(
        () => builder.addFace(warpedQuad),
        throwsA(isA<SkpWriteError>().having((e) => e.message, 'message', contains('not coplanar'))),
      );
    });

    test('non-planar input with autoTriangulate splits into 2 faces', () {
      final builder = create();
      builder.addFace(warpedQuad, autoTriangulate: true);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.root.faces.length, 2);
    });

    test('already-planar input stays a single face', () {
      final builder = create();
      builder.addFace(flatSquare, autoTriangulate: true);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.root.faces.length, 1);
    });
  });

  group('FaceHoles', () {
    test('a face with one hole self-parses with a boundary + hole loop', () {
      const wall = [
        (0.0, 0.0, 0.0), (200.0, 0.0, 0.0), (200.0, 100.0, 0.0), (0.0, 100.0, 0.0),
      ];
      const window = [
        (80.0, 30.0, 0.0), (120.0, 30.0, 0.0), (120.0, 70.0, 0.0), (80.0, 70.0, 0.0),
      ];
      final builder = create();
      builder.addFace(wall, holes: [window]);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      final face = model.root.faces.values.first;
      expect(face.loops.length, 2);
      expect(face.loops[0].length, 4);
      expect(face.loops[1].length, 4);
      expect(model.root.edges.length, 8); // 4 boundary + 4 hole, no sharing
    });

    test('a hole off the face plane throws', () {
      const wall = [
        (0.0, 0.0, 0.0), (200.0, 0.0, 0.0), (200.0, 100.0, 0.0), (0.0, 100.0, 0.0),
      ];
      const badHole = [
        (80.0, 30.0, 5.0), (120.0, 30.0, 5.0), (120.0, 70.0, 5.0), (80.0, 70.0, 5.0),
      ];
      final builder = create();
      expect(
        () => builder.addFace(wall, holes: [badHole]),
        throwsA(isA<SkpWriteError>()),
      );
    });
  });

  group('Materials', () {
    test('add_material dedupes by name', () {
      final builder = create();
      final a = builder.addMaterial('Red', [255, 0, 0]);
      final b = builder.addMaterial('Red', [0, 255, 0]); // ignored: already registered
      expect(a, b);
      expect(builder.materialsByName['Red'], a);
    });

    test('solid material color round-trips', () {
      final builder = create();
      final red = builder.addMaterial('Red', [255, 10, 20, 200]);
      builder.addFace(square, material: red);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      final mat = model.materials.single;
      expect(mat.name, 'Red');
      expect(mat.color, (255, 10, 20, 200));
    });

    test('front and back materials are independent', () {
      final builder = create();
      final red = builder.addMaterial('Red', [255, 0, 0]);
      final blue = builder.addMaterial('Blue', [0, 0, 255]);
      builder.addFace(square, material: red, backMaterial: blue);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      final face = model.root.faces.values.first;
      final frontName = model.materialsById[face.materialId]?.name;
      final backName = model.materialsById[face.backMaterialId]?.name;
      expect(frontName, 'Red');
      expect(backName, 'Blue');
    });
  });

  group('Textures', () {
    List<int> makeFakePng() => [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, ...List.generate(32, (i) => i)];
    List<int> makeFakeJpeg() => [0xFF, 0xD8, 0xFF, 0xE0, ...List.generate(32, (i) => 255 - i)];

    test('a PNG texture self-parses with texture data intact', () {
      final tmpDir = Directory.systemTemp.createTempSync('openskp_tex_');
      final pngPath = '${tmpDir.path}${Platform.pathSeparator}tex.png';
      File(pngPath).writeAsBytesSync(makeFakePng());
      try {
        final builder = create();
        final tex = builder.addTextureMaterial('Brick', pngPath);
        builder.addFace(square, material: tex);
        final model = SkpFile.fromBuffer(builder.toBytes()).parse();
        final mat = model.materials.single;
        expect(mat.name, 'Brick');
        expect(mat.texture, isNotNull);
        expect(mat.texture!.data, equals(makeFakePng()));
      } finally {
        tmpDir.deleteSync(recursive: true);
      }
    });

    test('an unrecognized image format throws', () {
      final tmpDir = Directory.systemTemp.createTempSync('openskp_tex_');
      final badPath = '${tmpDir.path}${Platform.pathSeparator}tex.jpg';
      File(badPath).writeAsBytesSync([1, 2, 3, 4]);
      try {
        final builder = create();
        expect(
          () => builder.addTextureMaterial('Bad', badPath),
          throwsA(isA<SkpWriteError>()),
        );
      } finally {
        tmpDir.deleteSync(recursive: true);
      }
    });

    test('PNG and JPEG textures work together', () {
      final tmpDir = Directory.systemTemp.createTempSync('openskp_tex_');
      final pngPath = '${tmpDir.path}${Platform.pathSeparator}tex.png';
      final jpgPath = '${tmpDir.path}${Platform.pathSeparator}tex.jpg';
      File(pngPath).writeAsBytesSync(makeFakePng());
      File(jpgPath).writeAsBytesSync(makeFakeJpeg());
      try {
        final builder = create();
        final pngMat = builder.addTextureMaterial('PngTex', pngPath);
        final jpgMat = builder.addTextureMaterial('JpgTex', jpgPath);
        builder.addFace(square, material: pngMat);
        builder.addFace(
          [(0.0, 0.0, 10.0), (100.0, 0.0, 10.0), (100.0, 100.0, 10.0), (0.0, 100.0, 10.0)],
          material: jpgMat,
        );
        final model = SkpFile.fromBuffer(builder.toBytes()).parse();
        expect(model.materials.map((m) => m.name).toSet(), {'PngTex', 'JpgTex'});
      } finally {
        tmpDir.deleteSync(recursive: true);
      }
    });

    test('addImage places a real Image entity, not a plain textured face', () {
      final tmpDir = Directory.systemTemp.createTempSync('openskp_tex_');
      final pngPath = '${tmpDir.path}${Platform.pathSeparator}tex.png';
      File(pngPath).writeAsBytesSync(makeFakePng());
      try {
        final builder = create();
        builder.addImage(
          pngPath, 48, 36,
          translation: (0.0, 0.0, 40.0),
          rotation: ((1.0, 0.0, 0.0), pi / 2),
        );
        final model = SkpFile.fromBuffer(builder.toBytes()).parse();

        final imageDefs = model.definitions.values.where((d) => d.isImage).toList();
        expect(imageDefs, hasLength(1));
        expect(imageDefs.single.faces, hasLength(1));
        expect(model.root.instances, hasLength(1));
        expect(model.root.instances.single.refIdx, imageDefs.single.id);
      } finally {
        tmpDir.deleteSync(recursive: true);
      }
    });
  });

  group('Layers', () {
    test('add_layer dedupes by name', () {
      final builder = create();
      final a = builder.addLayer('Roof');
      final b = builder.addLayer('Roof');
      expect(a, b);
    });

    test('layer color and hidden flag round-trip', () {
      final builder = create();
      final roof = builder.addLayer('Roof', color: [10, 20, 30], hidden: true);
      builder.addFace(square, layer: roof);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      final layer = model.layers.firstWhere((l) => l.name == 'Roof');
      expect(layer.colorR, 10);
      expect(layer.colorG, 20);
      expect(layer.colorB, 30);
      expect(layer.hidden, isTrue);
    });

    test('many layers self-parse with correct names', () {
      final builder = create();
      final names = [for (var i = 0; i < 25; i++) 'Layer$i'];
      for (final n in names) {
        builder.addLayer(n);
      }
      builder.addFace(square, layer: builder.layersByName[names.last]);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.layers.map((l) => l.name).toSet(), {'Layer0', ...names});
    });
  });

  group('CurvedEdges', () {
    test('a circle self-parses as a single closed face', () {
      final builder = create();
      builder.addCircle((50.0, 50.0, 0.0), (0.0, 0.0, 1.0), 40.0, numSegments: 8);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.root.edges.length, 8);
      expect(model.root.faces.length, 1);
    });

    test('a circle face normal matches the requested normal (winding check)', () {
      final builder = create();
      builder.addCircle((0.0, 0.0, 0.0), (0.0, 0.0, 1.0), 10.0, numSegments: 12);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      final normal = model.root.faces.values.first.normal!;
      expect(normal.$1, closeTo(0.0, 1e-6));
      expect(normal.$2, closeTo(0.0, 1e-6));
      expect(normal.$3, closeTo(1.0, 1e-6));
    });

    test('add_circle rejects a bad segment count', () {
      final builder = create();
      expect(
        () => builder.addCircle((0.0, 0.0, 0.0), (0.0, 0.0, 1.0), 10.0, numSegments: 2),
        throwsA(isA<SkpWriteError>()),
      );
      expect(
        () => builder.addCircle((0.0, 0.0, 0.0), (0.0, 0.0, 1.0), 10.0, numSegments: 256),
        throwsA(isA<SkpWriteError>()),
      );
    });

    test('an arc self-parses as an open chain with no face', () {
      final builder = create();
      builder.addArc((50.0, 50.0, 0.0), (0.0, 0.0, 1.0), 40.0, 0.0, pi / 2, numSegments: 6);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.root.edges.length, 6);
      expect(model.root.faces.length, 0);
    });

    test('arc endpoints match the requested sweep', () {
      final builder = create();
      builder.addArc((50.0, 50.0, 0.0), (0.0, 0.0, 1.0), 40.0, 0.0, pi / 2, numSegments: 6);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      final coords = model.root.vertices.values
          .map((v) => (
                (v.x * 1e6).round() / 1e6,
                (v.y * 1e6).round() / 1e6,
                (v.z * 1e6).round() / 1e6,
              ))
          .toSet();
      expect(coords, contains((90.0, 50.0, 0.0)));
      expect(coords, contains((50.0, 90.0, 0.0)));
    });

    test('add_arc rejects equal start/end angles', () {
      final builder = create();
      expect(
        () => builder.addArc((0.0, 0.0, 0.0), (0.0, 0.0, 1.0), 10.0, 1.0, 1.0),
        throwsA(isA<SkpWriteError>()),
      );
    });

    test('an arc and a circle sharing a center dedupe their overlapping vertex', () {
      final builder = create();
      builder.addArc((0.0, 0.0, 0.0), (0.0, 0.0, 1.0), 10.0, 0.0, pi, numSegments: 4);
      builder.addCircle((0.0, 0.0, 0.0), (0.0, 0.0, 1.0), 10.0, numSegments: 4);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      final coords = model.root.vertices.values
          .map((v) => ((v.x * 1e6).round() / 1e6, (v.y * 1e6).round() / 1e6, (v.z * 1e6).round() / 1e6))
          .toList();
      expect(coords.length, coords.toSet().length, reason: 'no duplicate CVertex for a shared point');
      expect(coords.where((c) => c == (10.0, 0.0, 0.0)).length, 1);
    });

    test('an open polyline self-parses with no face', () {
      final builder = create();
      builder.addPolyline([(0.0, 0.0, 0.0), (10.0, 10.0, 0.0), (20.0, 0.0, 0.0), (30.0, 10.0, 0.0)]);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.root.edges.length, 3);
      expect(model.root.faces.length, 0);
    });

    test('a closed polyline wraps around', () {
      final builder = create();
      builder.addPolyline(
        [(0.0, 0.0, 0.0), (10.0, 0.0, 0.0), (10.0, 10.0, 0.0), (0.0, 10.0, 0.0)],
        closed: true,
      );
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.root.edges.length, 4);
    });

    test('add_polyline rejects too few points', () {
      final builder = create();
      expect(() => builder.addPolyline([(0.0, 0.0, 0.0)]), throwsA(isA<SkpWriteError>()));
    });

    test('a circle inside a component definition round-trips', () {
      final builder = create();
      final wheel = builder.addComponentDefinition('Wheel', (def) {
        def.addCircle((0.0, 0.0, 0.0), (0.0, 0.0, 1.0), 15.0, numSegments: 10);
      });
      builder.addInstance(wheel);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.definitions.values.first.faces.length, 1);
    });
  });

  group('AttributeDicts', () {
    test('face attributes round-trip via dynamic_attributes-style dict', () {
      final builder = create();
      builder.addFace(square, attributes: {'partNumber': 'A-100', 'count': 7, 'weight': 3.5});
      // The reader's public model doesn't expose face-level attributes (see
      // edit.dart's own doc comment on this gap) - this test's job is only
      // to confirm the write path doesn't corrupt the file when attributes
      // are present, which self-parsing already proves.
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.root.faces.length, 1);
    });

    test('bool attribute values are rejected', () {
      final builder = create();
      expect(
        () => builder.addFace(square, attributes: {'flag': true}),
        throwsA(isA<SkpWriteError>()),
      );
    });

    test('out-of-range int attribute values are rejected', () {
      final builder = create();
      expect(
        () => builder.addFace(square, attributes: {'big': 1 << 40}),
        throwsA(isA<SkpWriteError>()),
      );
    });

    test('instance dynamic attributes round-trip through Instance.properties', () {
      // Was reader-side broken (LegacyReaders.extractLegacyDynamicProperties
      // compared the *class* name Archive.readObject returns for each
      // CAttributeContainer child - always "CAttributeNamed" - against the
      // dictionary's own name instead of comparing DictRec.name, so
      // "dynamic_attributes" was never recognized) - fixed 2026-08-26,
      // ported from the same fix in Python's legacy.py. Now genuinely
      // round-trips.
      final builder = create();
      final chair = builder.addComponentDefinition('Chair', (def) {
        def.addFace(square);
      });
      builder.addInstance(
        chair,
        attributes: {'sku': 'CH-1', 'qty': 3},
        attributeDictName: 'dynamic_attributes',
      );
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.root.instances.single.name, 'Chair');
      expect(model.root.instances.single.properties, {'sku': 'CH-1', 'qty': '3'});
    });
  });

  group('ComponentDefinitions', () {
    test('a basic definition and instance round-trip', () {
      final builder = create();
      final chair = builder.addComponentDefinition('Chair', (def) {
        def.addFace(square);
      });
      builder.addInstance(chair);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.root.instances.length, 1);
      final inst = model.root.instances.single;
      expect(inst.name, 'Chair');
      expect(inst.matrix.length, 13);
      expect(inst.matrix[0], closeTo(1.0, 1e-9));
      expect(inst.matrix[4], closeTo(1.0, 1e-9));
      expect(inst.matrix[8], closeTo(1.0, 1e-9));
      expect(inst.matrix[12], closeTo(1.0, 1e-9));
    });

    test('multiple instances share one definition', () {
      final builder = create();
      final chair = builder.addComponentDefinition('Chair', (def) {
        def.addFace(square);
      });
      for (var i = 0; i < 5; i++) {
        builder.addInstance(chair, name: 'Chair$i', translation: (i * 40.0, 0.0, 0.0));
      }
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.root.instances.length, 5);
      expect(model.definitions.length, 1);
      final translations = model.root.instances.map((i) => i.matrix[9]).toList()..sort();
      expect(translations, [0.0, 40.0, 80.0, 120.0, 160.0]);
    });

    test('an explicit transform matrix is applied', () {
      final builder = create();
      final post = builder.addComponentDefinition('Post', (def) {
        def.addFace(square);
      });
      // 2x scale on X only
      builder.addInstance(post, matrix3x3: (2.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0));
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.root.instances.single.matrix[0], 2.0);
    });

    test('an empty definition throws', () {
      final builder = create();
      expect(
        () => builder.addComponentDefinition('Empty', (def) {}),
        throwsA(isA<SkpWriteError>().having((e) => e.message, 'message', contains('no geometry'))),
      );
    });

    test('adding a face after the definition closed throws', () {
      final builder = create();
      late ComponentDefinitionBuilder chair;
      chair = builder.addComponentDefinition('Chair', (def) {
        def.addFace(square);
      });
      expect(() => chair.addFace(square), throwsA(isA<SkpWriteError>()));
    });

    test('add_material after a definition started throws', () {
      final builder = create();
      builder.addComponentDefinition('Chair', (def) {
        def.addFace(square);
      });
      expect(
        () => builder.addMaterial('TooLate', [0, 0, 0]),
        throwsA(isA<SkpWriteError>().having((e) => e.message, 'message', contains('addComponentDefinition'))),
      );
    });

    test('add_component_definition after add_face throws', () {
      final builder = create();
      builder.addFace(square);
      expect(
        () => builder.addComponentDefinition('TooLate', (def) {}),
        throwsA(isA<SkpWriteError>()),
      );
    });

    test('definition geometry and root geometry share no vertices', () {
      final builder = create();
      final chair = builder.addComponentDefinition('Chair', (def) {
        def.addFace(square);
      });
      builder.addFace(square); // same coordinates, root level
      builder.addInstance(chair);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.root.faces.length, 1); // only the root-level face
      expect(model.root.edges.length, 4); // its own 4 edges, not shared
    });
  });

  group('Groups', () {
    test('a basic group places itself on close', () {
      final builder = create();
      builder.addGroup((def) {
        def.addFace(square);
      }, name: 'Table', translation: (50.0, 0.0, 0.0));
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.root.instances.length, 1);
      final inst = model.root.instances.single;
      expect(inst.name, 'Table');
      expect(inst.matrix[9], 50.0);
      // ground truth: unlike CComponentInstance, CGroup carries no dynamic
      // attributes - properties should be empty.
      expect(inst.properties, isEmpty);
    });

    test('a hidden group round-trips', () {
      final builder = create();
      builder.addGroup((def) {
        def.addFace(square);
      }, name: 'Table', hidden: true);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.root.instances.single.hidden, isTrue);
    });

    test('a group without geometry throws', () {
      final builder = create();
      expect(
        () => builder.addGroup((def) {}, name: 'Empty'),
        throwsA(isA<SkpWriteError>()),
      );
    });

    test('the default group name is "Group"', () {
      final builder = create();
      builder.addGroup((def) {
        def.addFace(square);
      });
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.root.instances.single.name, 'Group');
    });

    test('groups and component instances coexist at the root', () {
      final builder = create();
      final chair = builder.addComponentDefinition('Chair', (def) {
        def.addFace(square);
      });
      builder.addGroup((def) {
        def.addFace(square);
      }, name: 'Table', translation: (100.0, 0.0, 0.0));
      builder.addInstance(chair, translation: (0.0, 100.0, 0.0));
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.root.instances.length, 2);
      expect(model.root.instances.map((i) => i.name).toSet(), {'Table', 'Chair'});
    });

    test('many definitions, groups, and instances self-parse at scale', () {
      final builder = create();
      final defs = <ComponentDefinitionBuilder>[];
      for (var d = 0; d < 20; d++) {
        defs.add(builder.addComponentDefinition('Def$d', (def) {
          def.addFace(square);
        }));
      }
      for (var g = 0; g < 10; g++) {
        builder.addGroup((def) {
          def.addFace(square);
        }, name: 'Grp$g', translation: (g * 30.0, 500.0, 0.0));
      }
      for (var i = 0; i < 40; i++) {
        builder.addInstance(defs[i % 20], name: 'Inst$i', translation: (i * 25.0, 1000.0, 0.0));
      }
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.root.instances.length, 50); // 10 groups + 40 instances
      // A CGroup's placement still references a real CComponentDefinition
      // underneath (structurally, a group's contents are stored exactly
      // like a component definition's - see write_group's own note) - so
      // the reader's definitions map includes the 10 implicit group
      // definitions alongside the 20 explicit ones.
      expect(model.definitions.length, 30);
    });
  });

  group('NestedDefinitions', () {
    test('a definition nests an instance of another definition', () {
      final builder = create();
      final wheel = builder.addComponentDefinition('Wheel', (def) {
        def.addFace(square);
      });
      final car = builder.addComponentDefinition('Car', (def) {
        def.addInstance(wheel, translation: (0.0, 0.0, 0.0));
        def.addInstance(wheel, translation: (200.0, 0.0, 0.0));
      });
      builder.addInstance(car);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      // Root level only ever sees Car - Wheel is never placed there.
      expect(model.root.instances.length, 1);
      expect(model.root.instances.single.name, 'Car');
      final carDef = model.definitions.values.firstWhere((d) => d.name == 'Car');
      expect(carDef.instances.length, 2);
      expect(carDef.instances.every((i) => i.name == 'Wheel'), isTrue);
    });

    test('a definition cannot nest an instance of itself', () {
      final builder = create();
      expect(
        () => builder.addComponentDefinition('Loop', (def) {
          def.addFace(square);
          def.addInstance(def);
        }),
        throwsA(isA<SkpWriteError>()),
      );
    });

    test('nesting a definition from a different builder throws', () {
      final other = create();
      final foreign = other.addComponentDefinition('Foreign', (def) {
        def.addFace(square);
      });
      final builder = create();
      expect(
        () => builder.addComponentDefinition('Local', (def) {
          def.addFace(square);
          def.addInstance(foreign);
        }),
        throwsA(isA<SkpWriteError>()),
      );
    });
  });

  group('NestedGroups', () {
    test('a definition nests a group instance of another definition', () {
      final builder = create();
      final engine = builder.addComponentDefinition('Engine', (def) {
        def.addFace(square);
      });
      final car = builder.addComponentDefinition('Car', (def) {
        def.addFace(square);
        def.addGroupInstance(engine, translation: (50.0, 0.0, 10.0));
      });
      builder.addInstance(car);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      final carDef = model.definitions.values.firstWhere((d) => d.name == 'Car');
      expect(carDef.faces.length, 1);
      expect(carDef.instances.length, 1);
      expect(carDef.instances.single.name, 'Engine');
    });
  });

  group('InstanceRotation', () {
    test('rotation matches an equivalent explicit matrix3x3', () {
      // `rotation:` is documented as a convenience for a hand-derived
      // `matrix3x3:` via the same Rodrigues formula ([rotationMatrix3x3],
      // also exported) - build one instance each way and confirm they
      // produce byte-identical transforms, rather than re-deriving the
      // expected numbers by hand (error-prone to get the sign/row-vs-
      // column convention right independently).
      final builder = create();
      final chair = builder.addComponentDefinition('Chair', (def) {
        def.addFace(square);
      });
      const axis = (0.0, 0.0, 1.0);
      final angle = pi / 2;
      builder.addInstance(chair, name: 'ViaRotation', rotation: (axis, angle));
      builder.addInstance(chair, name: 'ViaMatrix', matrix3x3: rotationMatrix3x3(axis, angle));
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      final byName = {for (final i in model.root.instances) i.name: i.matrix};
      final viaRotation = byName['ViaRotation']!;
      final viaMatrix = byName['ViaMatrix']!;
      for (var i = 0; i < 9; i++) {
        expect(viaRotation[i], closeTo(viaMatrix[i], 1e-12));
      }
      // Sanity check it's a genuine 90-degree turn, not an identity/no-op:
      // the X axis (1, 0, 0) should map to +/-Y, not stay along X.
      expect(viaRotation[0].abs(), lessThan(1e-9));
      expect(viaRotation[1].abs(), closeTo(1.0, 1e-9));
    });

    test('matrix3x3 and rotation cannot both be given', () {
      final builder = create();
      final chair = builder.addComponentDefinition('Chair', (def) {
        def.addFace(square);
      });
      expect(
        () => builder.addInstance(
          chair,
          matrix3x3: (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0),
          rotation: ((0.0, 0.0, 1.0), 1.0),
        ),
        throwsA(isA<SkpWriteError>()),
      );
    });
  });

  group('UnicodeNames', () {
    const name = 'Rouge Écarlate étoile';

    test('a material name round-trips exactly', () {
      final builder = create();
      final mat = builder.addMaterial(name, [255, 0, 0]);
      builder.addFace(square, material: mat);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.materials.single.name, name);
    });

    test('a layer name round-trips exactly', () {
      final builder = create();
      final layer = builder.addLayer(name);
      builder.addFace(square, layer: layer);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.layers.any((l) => l.name == name), isTrue);
    });

    test('a component definition name round-trips exactly', () {
      final builder = create();
      final def = builder.addComponentDefinition(name, (def) {
        def.addFace(square);
      });
      builder.addInstance(def);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.definitions.values.single.name, name);
    });
  });

  group('BuilderErrors', () {
    test('saving with no geometry throws', () {
      expect(
        () => create().toBytes(),
        throwsA(isA<SkpWriteError>().having((e) => e.message, 'message', contains('no geometry'))),
      );
    });

    test('a face with fewer than 3 points throws', () {
      final builder = create();
      expect(
        () => builder.addFace([(0.0, 0.0, 0.0), (1.0, 0.0, 0.0)]),
        throwsA(isA<SkpWriteError>()),
      );
    });

    test('collinear points throw', () {
      final builder = create();
      expect(
        () => builder.addFace([(0.0, 0.0, 0.0), (1.0, 0.0, 0.0), (2.0, 0.0, 0.0)]),
        throwsA(isA<SkpWriteError>().having((e) => e.message, 'message', contains('collinear'))),
      );
    });

    test('non-planar points throw', () {
      final builder = create();
      expect(
        () => builder.addFace([
          (0.0, 0.0, 0.0), (100.0, 0.0, 0.0), (100.0, 100.0, 0.0), (0.0, 100.0, 50.0),
        ]),
        throwsA(isA<SkpWriteError>().having((e) => e.message, 'message', contains('not coplanar'))),
      );
    });
  });

  group('SlotBoundary', () {
    // Real-scale reproduction: enough unique (non-shared-vertex) triangles
    // to push the file's total archive-slot count past 32,767 - the exact
    // condition that corrupted large flattened-geometry exports before the
    // matching Python fix. Deliberately unique vertices per triangle
    // (~11 new slots each) rather than a shared grid, landing the crossing
    // at an unpredictable slot number - the same worst case a flattened
    // CAD import produces.
    SkpBuilder buildLarge(int n) {
      final builder = create();
      for (var i = 0; i < n; i++) {
        final x = i * 10.0;
        builder.addFace([(x, 0.0, 0.0), (x + 1.0, 0.0, 0.0), (x, 1.0, 0.0)]);
      }
      return builder;
    }

    test('next_slot actually crosses the 0x7FFF boundary', () {
      final builder = buildLarge(3200);
      expect(builder.debugGeometryNextSlot! > 0x7FFF, isTrue);
    });

    test('round-trips through the own reader with the exact face count', () {
      final builder = buildLarge(3200);
      final model = SkpFile.fromBuffer(builder.toBytes()).parse();
      expect(model.root.faces.length, 3200);
    });

    test('matches Python byte-for-byte across the slot boundary', () {
      final builder = buildLarge(3200);
      final expected = File('$referenceDir/slot_boundary.skp').readAsBytesSync();
      expect(builder.toBytes(), equals(expected));
    }, timeout: const Timeout.factor(4));
  });

  group('ScaffoldIntegrity', () {
    test('the bundled scaffold matches the fixture the reader tests also use', () {
      // The same blank_v17.skp bytes are bundled 3 ways in this repo: as a
      // raw file for the writer (lib/src/scaffold/blank_v17.skp), embedded
      // as a base64 Dart constant for actual runtime use
      // (lib/src/scaffold_data.dart), and as a reader-side test fixture
      // (test/fixtures/blank_v17.skp) - confirm all three agree.
      final fromLib = File('${Directory.current.path}/lib/src/scaffold/blank_v17.skp').readAsBytesSync();
      final fromFixture = File('${Directory.current.path}/test/fixtures/blank_v17.skp').readAsBytesSync();
      expect(fromLib, equals(fromFixture));
    });
  });
}
